#![allow(
    warnings,
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    clippy::cargo,
    clippy::style,
    clippy::complexity,
    clippy::correctness,
    clippy::perf,
    clippy::suspicious
)]
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

use crate::proto::v1::types_generated::skyrim_relive::v_1::*;

#[allow(unused_imports, dead_code)]
pub mod skyrim_relive {

    use crate::proto::v1::types_generated::skyrim_relive::v_1::*;
    #[allow(unused_imports, dead_code)]
    pub mod v_1 {

        use crate::proto::v1::types_generated::skyrim_relive::v_1::*;

        pub enum HelloOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Hello<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Hello<'a> {
            type Inner = Hello<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> Hello<'a> {
            pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
            pub const VT_CLIENT_PROTOCOL_VERSION: ::flatbuffers::VOffsetT = 6;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Hello { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args HelloArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<Hello<'bldr>> {
                let mut builder = HelloBuilder::new(_fbb);
                if let Some(x) = args.name {
                    builder.add_name(x);
                }
                builder.add_client_protocol_version(args.client_protocol_version);
                builder.finish()
            }

            #[inline]
            pub fn name(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(Hello::VT_NAME, None)
                }
            }
            #[inline]
            pub fn client_protocol_version(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u8>(Hello::VT_CLIENT_PROTOCOL_VERSION, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for Hello<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "name",
                        Self::VT_NAME,
                        false,
                    )?
                    .visit_field::<u8>(
                        "client_protocol_version",
                        Self::VT_CLIENT_PROTOCOL_VERSION,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct HelloArgs<'a> {
            pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub client_protocol_version: u8,
        }
        impl<'a> Default for HelloArgs<'a> {
            #[inline]
            fn default() -> Self {
                HelloArgs {
                    name: None,
                    client_protocol_version: 0,
                }
            }
        }

        pub struct HelloBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HelloBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(Hello::VT_NAME, name);
            }
            #[inline]
            pub fn add_client_protocol_version(&mut self, client_protocol_version: u8) {
                self.fbb_.push_slot::<u8>(
                    Hello::VT_CLIENT_PROTOCOL_VERSION,
                    client_protocol_version,
                    0,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> HelloBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                HelloBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Hello<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Hello<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Hello");
                ds.field("name", &self.name());
                ds.field("client_protocol_version", &self.client_protocol_version());
                ds.finish()
            }
        }
        pub enum WelcomeOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Welcome<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Welcome<'a> {
            type Inner = Welcome<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> Welcome<'a> {
            pub const VT_PLAYER_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_SERVER_TICK_RATE_HZ: ::flatbuffers::VOffsetT = 6;
            pub const VT_SERVER_SNAPSHOT_RATE_HZ: ::flatbuffers::VOffsetT = 8;
            pub const VT_YOUR_ADDR: ::flatbuffers::VOffsetT = 10;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Welcome { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args WelcomeArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<Welcome<'bldr>> {
                let mut builder = WelcomeBuilder::new(_fbb);
                if let Some(x) = args.your_addr {
                    builder.add_your_addr(x);
                }
                builder.add_player_id(args.player_id);
                builder.add_server_snapshot_rate_hz(args.server_snapshot_rate_hz);
                builder.add_server_tick_rate_hz(args.server_tick_rate_hz);
                builder.finish()
            }

            #[inline]
            pub fn player_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(Welcome::VT_PLAYER_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn server_tick_rate_hz(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u8>(Welcome::VT_SERVER_TICK_RATE_HZ, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn server_snapshot_rate_hz(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u8>(Welcome::VT_SERVER_SNAPSHOT_RATE_HZ, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn your_addr(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(Welcome::VT_YOUR_ADDR, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for Welcome<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("player_id", Self::VT_PLAYER_ID, false)?
                    .visit_field::<u8>("server_tick_rate_hz", Self::VT_SERVER_TICK_RATE_HZ, false)?
                    .visit_field::<u8>(
                        "server_snapshot_rate_hz",
                        Self::VT_SERVER_SNAPSHOT_RATE_HZ,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "your_addr",
                        Self::VT_YOUR_ADDR,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct WelcomeArgs<'a> {
            pub player_id: u32,
            pub server_tick_rate_hz: u8,
            pub server_snapshot_rate_hz: u8,
            pub your_addr: Option<::flatbuffers::WIPOffset<&'a str>>,
        }
        impl<'a> Default for WelcomeArgs<'a> {
            #[inline]
            fn default() -> Self {
                WelcomeArgs {
                    player_id: 0,
                    server_tick_rate_hz: 0,
                    server_snapshot_rate_hz: 0,
                    your_addr: None,
                }
            }
        }

        pub struct WelcomeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WelcomeBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_player_id(&mut self, player_id: u32) {
                self.fbb_
                    .push_slot::<u32>(Welcome::VT_PLAYER_ID, player_id, 0);
            }
            #[inline]
            pub fn add_server_tick_rate_hz(&mut self, server_tick_rate_hz: u8) {
                self.fbb_
                    .push_slot::<u8>(Welcome::VT_SERVER_TICK_RATE_HZ, server_tick_rate_hz, 0);
            }
            #[inline]
            pub fn add_server_snapshot_rate_hz(&mut self, server_snapshot_rate_hz: u8) {
                self.fbb_.push_slot::<u8>(
                    Welcome::VT_SERVER_SNAPSHOT_RATE_HZ,
                    server_snapshot_rate_hz,
                    0,
                );
            }
            #[inline]
            pub fn add_your_addr(&mut self, your_addr: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    Welcome::VT_YOUR_ADDR,
                    your_addr,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> WelcomeBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                WelcomeBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Welcome<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Welcome<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Welcome");
                ds.field("player_id", &self.player_id());
                ds.field("server_tick_rate_hz", &self.server_tick_rate_hz());
                ds.field("server_snapshot_rate_hz", &self.server_snapshot_rate_hz());
                ds.field("your_addr", &self.your_addr());
                ds.finish()
            }
        }
        pub enum HeartbeatOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Heartbeat<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Heartbeat<'a> {
            type Inner = Heartbeat<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> Heartbeat<'a> {
            pub const VT_CLIENT_TIME_MS: ::flatbuffers::VOffsetT = 4;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Heartbeat { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args HeartbeatArgs,
            ) -> ::flatbuffers::WIPOffset<Heartbeat<'bldr>> {
                let mut builder = HeartbeatBuilder::new(_fbb);
                builder.add_client_time_ms(args.client_time_ms);
                builder.finish()
            }

            #[inline]
            pub fn client_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(Heartbeat::VT_CLIENT_TIME_MS, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for Heartbeat<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("client_time_ms", Self::VT_CLIENT_TIME_MS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct HeartbeatArgs {
            pub client_time_ms: u64,
        }
        impl<'a> Default for HeartbeatArgs {
            #[inline]
            fn default() -> Self {
                HeartbeatArgs { client_time_ms: 0 }
            }
        }

        pub struct HeartbeatBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HeartbeatBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_client_time_ms(&mut self, client_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(Heartbeat::VT_CLIENT_TIME_MS, client_time_ms, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> HeartbeatBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                HeartbeatBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Heartbeat<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Heartbeat<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Heartbeat");
                ds.field("client_time_ms", &self.client_time_ms());
                ds.finish()
            }
        }
        pub enum LeaveNotifyOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct LeaveNotify<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for LeaveNotify<'a> {
            type Inner = LeaveNotify<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> LeaveNotify<'a> {
            pub const VT_REASON: ::flatbuffers::VOffsetT = 4;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                LeaveNotify { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args LeaveNotifyArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<LeaveNotify<'bldr>> {
                let mut builder = LeaveNotifyBuilder::new(_fbb);
                if let Some(x) = args.reason {
                    builder.add_reason(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn reason(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(LeaveNotify::VT_REASON, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for LeaveNotify<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "reason",
                        Self::VT_REASON,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct LeaveNotifyArgs<'a> {
            pub reason: Option<::flatbuffers::WIPOffset<&'a str>>,
        }
        impl<'a> Default for LeaveNotifyArgs<'a> {
            #[inline]
            fn default() -> Self {
                LeaveNotifyArgs { reason: None }
            }
        }

        pub struct LeaveNotifyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LeaveNotifyBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_reason(&mut self, reason: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    LeaveNotify::VT_REASON,
                    reason,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> LeaveNotifyBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                LeaveNotifyBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<LeaveNotify<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for LeaveNotify<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("LeaveNotify");
                ds.field("reason", &self.reason());
                ds.finish()
            }
        }
        pub enum DisconnectOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Disconnect<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Disconnect<'a> {
            type Inner = Disconnect<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> Disconnect<'a> {
            pub const VT_CODE: ::flatbuffers::VOffsetT = 4;
            pub const VT_REASON: ::flatbuffers::VOffsetT = 6;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Disconnect { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args DisconnectArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<Disconnect<'bldr>> {
                let mut builder = DisconnectBuilder::new(_fbb);
                if let Some(x) = args.reason {
                    builder.add_reason(x);
                }
                builder.add_code(args.code);
                builder.finish()
            }

            #[inline]
            pub fn code(&self) -> DisconnectCode {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<DisconnectCode>(Disconnect::VT_CODE, Some(DisconnectCode::Ok))
                        .unwrap()
                }
            }
            #[inline]
            pub fn reason(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(Disconnect::VT_REASON, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for Disconnect<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<DisconnectCode>("code", Self::VT_CODE, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "reason",
                        Self::VT_REASON,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct DisconnectArgs<'a> {
            pub code: DisconnectCode,
            pub reason: Option<::flatbuffers::WIPOffset<&'a str>>,
        }
        impl<'a> Default for DisconnectArgs<'a> {
            #[inline]
            fn default() -> Self {
                DisconnectArgs {
                    code: DisconnectCode::Ok,
                    reason: None,
                }
            }
        }

        pub struct DisconnectBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DisconnectBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_code(&mut self, code: DisconnectCode) {
                self.fbb_.push_slot::<DisconnectCode>(
                    Disconnect::VT_CODE,
                    code,
                    DisconnectCode::Ok,
                );
            }
            #[inline]
            pub fn add_reason(&mut self, reason: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(Disconnect::VT_REASON, reason);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> DisconnectBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                DisconnectBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Disconnect<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Disconnect<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Disconnect");
                ds.field("code", &self.code());
                ds.field("reason", &self.reason());
                ds.finish()
            }
        }
    } // pub mod v1
} // pub mod skyrim_relive
