#![allow(
    warnings,
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    clippy::cargo,
    clippy::style,
    clippy::complexity,
    clippy::correctness,
    clippy::perf,
    clippy::suspicious
)]
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod skyrim_relive {

    #[allow(unused_imports, dead_code)]
    pub mod v_1 {

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_MESSAGE_TYPE: u8 = 1;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_MESSAGE_TYPE: u8 = 33;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_MESSAGE_TYPE: [MessageType; 9] = [
            MessageType::Hello,
            MessageType::Welcome,
            MessageType::Heartbeat,
            MessageType::LeaveNotify,
            MessageType::Disconnect,
            MessageType::PlayerInput,
            MessageType::WorldSnapshot,
            MessageType::CombatEvent,
            MessageType::DamageApply,
        ];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct MessageType(pub u8);
        #[allow(non_upper_case_globals)]
        impl MessageType {
            pub const Hello: Self = Self(1);
            pub const Welcome: Self = Self(2);
            pub const Heartbeat: Self = Self(3);
            pub const LeaveNotify: Self = Self(4);
            pub const Disconnect: Self = Self(5);
            pub const PlayerInput: Self = Self(16);
            pub const WorldSnapshot: Self = Self(17);
            pub const CombatEvent: Self = Self(32);
            pub const DamageApply: Self = Self(33);

            pub const ENUM_MIN: u8 = 1;
            pub const ENUM_MAX: u8 = 33;
            pub const ENUM_VALUES: &'static [Self] = &[
                Self::Hello,
                Self::Welcome,
                Self::Heartbeat,
                Self::LeaveNotify,
                Self::Disconnect,
                Self::PlayerInput,
                Self::WorldSnapshot,
                Self::CombatEvent,
                Self::DamageApply,
            ];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::Hello => Some("Hello"),
                    Self::Welcome => Some("Welcome"),
                    Self::Heartbeat => Some("Heartbeat"),
                    Self::LeaveNotify => Some("LeaveNotify"),
                    Self::Disconnect => Some("Disconnect"),
                    Self::PlayerInput => Some("PlayerInput"),
                    Self::WorldSnapshot => Some("WorldSnapshot"),
                    Self::CombatEvent => Some("CombatEvent"),
                    Self::DamageApply => Some("DamageApply"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for MessageType {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for MessageType {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for MessageType {
            type Output = MessageType;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for MessageType {
            type Scalar = u8;
            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for MessageType {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for MessageType {}
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_DISCONNECT_CODE: u8 = 0;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_DISCONNECT_CODE: u8 = 6;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_DISCONNECT_CODE: [DisconnectCode; 7] = [
            DisconnectCode::Ok,
            DisconnectCode::VersionMismatch,
            DisconnectCode::Timeout,
            DisconnectCode::ServerFull,
            DisconnectCode::ServerShutdown,
            DisconnectCode::BadPacket,
            DisconnectCode::DuplicateName,
        ];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct DisconnectCode(pub u8);
        #[allow(non_upper_case_globals)]
        impl DisconnectCode {
            pub const Ok: Self = Self(0);
            pub const VersionMismatch: Self = Self(1);
            pub const Timeout: Self = Self(2);
            pub const ServerFull: Self = Self(3);
            pub const ServerShutdown: Self = Self(4);
            pub const BadPacket: Self = Self(5);
            pub const DuplicateName: Self = Self(6);

            pub const ENUM_MIN: u8 = 0;
            pub const ENUM_MAX: u8 = 6;
            pub const ENUM_VALUES: &'static [Self] = &[
                Self::Ok,
                Self::VersionMismatch,
                Self::Timeout,
                Self::ServerFull,
                Self::ServerShutdown,
                Self::BadPacket,
                Self::DuplicateName,
            ];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::Ok => Some("Ok"),
                    Self::VersionMismatch => Some("VersionMismatch"),
                    Self::Timeout => Some("Timeout"),
                    Self::ServerFull => Some("ServerFull"),
                    Self::ServerShutdown => Some("ServerShutdown"),
                    Self::BadPacket => Some("BadPacket"),
                    Self::DuplicateName => Some("DuplicateName"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for DisconnectCode {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for DisconnectCode {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for DisconnectCode {
            type Output = DisconnectCode;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for DisconnectCode {
            type Scalar = u8;
            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for DisconnectCode {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for DisconnectCode {}
    } // pub mod v1
} // pub mod skyrim_relive
