#![allow(
    warnings,
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    clippy::cargo,
    clippy::style,
    clippy::complexity,
    clippy::correctness,
    clippy::perf,
    clippy::suspicious
)]
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod skyrim_relive {

    #[allow(unused_imports, dead_code)]
    pub mod v_1 {

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_MESSAGE_TYPE: u8 = 1;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_MESSAGE_TYPE: u8 = 49;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_MESSAGE_TYPE: [MessageType; 11] = [
            MessageType::Hello,
            MessageType::Welcome,
            MessageType::Heartbeat,
            MessageType::LeaveNotify,
            MessageType::Disconnect,
            MessageType::PlayerInput,
            MessageType::WorldSnapshot,
            MessageType::CombatEvent,
            MessageType::DamageApply,
            MessageType::PlayerList,
            MessageType::ChatMessage,
        ];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct MessageType(pub u8);
        #[allow(non_upper_case_globals)]
        impl MessageType {
            pub const Hello: Self = Self(1);
            pub const Welcome: Self = Self(2);
            pub const Heartbeat: Self = Self(3);
            pub const LeaveNotify: Self = Self(4);
            pub const Disconnect: Self = Self(5);
            pub const PlayerInput: Self = Self(16);
            pub const WorldSnapshot: Self = Self(17);
            pub const CombatEvent: Self = Self(32);
            pub const DamageApply: Self = Self(33);
            pub const PlayerList: Self = Self(48);
            pub const ChatMessage: Self = Self(49);

            pub const ENUM_MIN: u8 = 1;
            pub const ENUM_MAX: u8 = 49;
            pub const ENUM_VALUES: &'static [Self] = &[
                Self::Hello,
                Self::Welcome,
                Self::Heartbeat,
                Self::LeaveNotify,
                Self::Disconnect,
                Self::PlayerInput,
                Self::WorldSnapshot,
                Self::CombatEvent,
                Self::DamageApply,
                Self::PlayerList,
                Self::ChatMessage,
            ];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::Hello => Some("Hello"),
                    Self::Welcome => Some("Welcome"),
                    Self::Heartbeat => Some("Heartbeat"),
                    Self::LeaveNotify => Some("LeaveNotify"),
                    Self::Disconnect => Some("Disconnect"),
                    Self::PlayerInput => Some("PlayerInput"),
                    Self::WorldSnapshot => Some("WorldSnapshot"),
                    Self::CombatEvent => Some("CombatEvent"),
                    Self::DamageApply => Some("DamageApply"),
                    Self::PlayerList => Some("PlayerList"),
                    Self::ChatMessage => Some("ChatMessage"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for MessageType {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for MessageType {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for MessageType {
            type Output = MessageType;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for MessageType {
            type Scalar = u8;
            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for MessageType {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for MessageType {}
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_DISCONNECT_CODE: u8 = 0;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_DISCONNECT_CODE: u8 = 6;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_DISCONNECT_CODE: [DisconnectCode; 7] = [
            DisconnectCode::Ok,
            DisconnectCode::VersionMismatch,
            DisconnectCode::Timeout,
            DisconnectCode::ServerFull,
            DisconnectCode::ServerShutdown,
            DisconnectCode::BadPacket,
            DisconnectCode::DuplicateName,
        ];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct DisconnectCode(pub u8);
        #[allow(non_upper_case_globals)]
        impl DisconnectCode {
            pub const Ok: Self = Self(0);
            pub const VersionMismatch: Self = Self(1);
            pub const Timeout: Self = Self(2);
            pub const ServerFull: Self = Self(3);
            pub const ServerShutdown: Self = Self(4);
            pub const BadPacket: Self = Self(5);
            pub const DuplicateName: Self = Self(6);

            pub const ENUM_MIN: u8 = 0;
            pub const ENUM_MAX: u8 = 6;
            pub const ENUM_VALUES: &'static [Self] = &[
                Self::Ok,
                Self::VersionMismatch,
                Self::Timeout,
                Self::ServerFull,
                Self::ServerShutdown,
                Self::BadPacket,
                Self::DuplicateName,
            ];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::Ok => Some("Ok"),
                    Self::VersionMismatch => Some("VersionMismatch"),
                    Self::Timeout => Some("Timeout"),
                    Self::ServerFull => Some("ServerFull"),
                    Self::ServerShutdown => Some("ServerShutdown"),
                    Self::BadPacket => Some("BadPacket"),
                    Self::DuplicateName => Some("DuplicateName"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for DisconnectCode {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for DisconnectCode {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for DisconnectCode {
            type Output = DisconnectCode;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for DisconnectCode {
            type Scalar = u8;
            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for DisconnectCode {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for DisconnectCode {}
        pub enum SkillEntryOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct SkillEntry<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for SkillEntry<'a> {
            type Inner = SkillEntry<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> SkillEntry<'a> {
            pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
            pub const VT_LEVEL: ::flatbuffers::VOffsetT = 6;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                SkillEntry { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args SkillEntryArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<SkillEntry<'bldr>> {
                let mut builder = SkillEntryBuilder::new(_fbb);
                builder.add_level(args.level);
                if let Some(x) = args.name {
                    builder.add_name(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn name(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(SkillEntry::VT_NAME, None)
                }
            }
            #[inline]
            pub fn level(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(SkillEntry::VT_LEVEL, Some(0.0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for SkillEntry<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "name",
                        Self::VT_NAME,
                        false,
                    )?
                    .visit_field::<f32>("level", Self::VT_LEVEL, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct SkillEntryArgs<'a> {
            pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub level: f32,
        }
        impl<'a> Default for SkillEntryArgs<'a> {
            #[inline]
            fn default() -> Self {
                SkillEntryArgs {
                    name: None,
                    level: 0.0,
                }
            }
        }

        pub struct SkillEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SkillEntryBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(SkillEntry::VT_NAME, name);
            }
            #[inline]
            pub fn add_level(&mut self, level: f32) {
                self.fbb_.push_slot::<f32>(SkillEntry::VT_LEVEL, level, 0.0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> SkillEntryBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                SkillEntryBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<SkillEntry<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for SkillEntry<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("SkillEntry");
                ds.field("name", &self.name());
                ds.field("level", &self.level());
                ds.finish()
            }
        }
    } // pub mod v1
} // pub mod skyrim_relive
