#![allow(
    warnings,
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    clippy::cargo,
    clippy::style,
    clippy::complexity,
    clippy::correctness,
    clippy::perf,
    clippy::suspicious
)]
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod skyrim_relive {

    #[allow(unused_imports, dead_code)]
    pub mod v_1 {

        // struct Vec3, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct Vec3(pub [u8; 12]);
        impl Default for Vec3 {
            fn default() -> Self {
                Self([0; 12])
            }
        }
        impl ::core::fmt::Debug for Vec3 {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("Vec3")
                    .field("x", &self.x())
                    .field("y", &self.y())
                    .field("z", &self.z())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Vec3 {}
        impl<'a> ::flatbuffers::Follow<'a> for Vec3 {
            type Inner = &'a Vec3;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a Vec3>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a Vec3 {
            type Inner = &'a Vec3;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<Vec3>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for Vec3 {
            type Output = Vec3;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const Vec3 as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Vec3 {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> Vec3 {
            #[allow(clippy::too_many_arguments)]
            pub fn new(x: f32, y: f32, z: f32) -> Self {
                let mut s = Self([0; 12]);
                s.set_x(x);
                s.set_y(y);
                s.set_z(z);
                s
            }

            pub fn x(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_x(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn y(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_y(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn z(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_z(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct Transform, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct Transform(pub [u8; 16]);
        impl Default for Transform {
            fn default() -> Self {
                Self([0; 16])
            }
        }
        impl ::core::fmt::Debug for Transform {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("Transform")
                    .field("pos", &self.pos())
                    .field("yaw", &self.yaw())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Transform {}
        impl<'a> ::flatbuffers::Follow<'a> for Transform {
            type Inner = &'a Transform;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a Transform>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a Transform {
            type Inner = &'a Transform;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<Transform>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for Transform {
            type Output = Transform;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const Transform as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Transform {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> Transform {
            #[allow(clippy::too_many_arguments)]
            pub fn new(pos: &Vec3, yaw: f32) -> Self {
                let mut s = Self([0; 16]);
                s.set_pos(pos);
                s.set_yaw(yaw);
                s
            }

            pub fn pos(&self) -> &Vec3 {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid struct in this slot
                unsafe { &*(self.0[0..].as_ptr() as *const Vec3) }
            }

            #[allow(clippy::identity_op)]
            pub fn set_pos(&mut self, x: &Vec3) {
                self.0[0..0 + 12].copy_from_slice(&x.0)
            }

            pub fn yaw(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[12..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_yaw(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[12..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct PlayerState, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct PlayerState(pub [u8; 20]);
        impl Default for PlayerState {
            fn default() -> Self {
                Self([0; 20])
            }
        }
        impl ::core::fmt::Debug for PlayerState {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("PlayerState")
                    .field("player_id", &self.player_id())
                    .field("transform", &self.transform())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for PlayerState {}
        impl<'a> ::flatbuffers::Follow<'a> for PlayerState {
            type Inner = &'a PlayerState;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a PlayerState>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a PlayerState {
            type Inner = &'a PlayerState;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<PlayerState>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for PlayerState {
            type Output = PlayerState;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const PlayerState as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for PlayerState {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> PlayerState {
            #[allow(clippy::too_many_arguments)]
            pub fn new(player_id: u32, transform: &Transform) -> Self {
                let mut s = Self([0; 20]);
                s.set_player_id(player_id);
                s.set_transform(transform);
                s
            }

            pub fn player_id(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_player_id(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn transform(&self) -> &Transform {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid struct in this slot
                unsafe { &*(self.0[4..].as_ptr() as *const Transform) }
            }

            #[allow(clippy::identity_op)]
            pub fn set_transform(&mut self, x: &Transform) {
                self.0[4..4 + 16].copy_from_slice(&x.0)
            }
        }

        pub enum PlayerInputOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct PlayerInput<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PlayerInput<'a> {
            type Inner = PlayerInput<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> PlayerInput<'a> {
            pub const VT_TRANSFORM: ::flatbuffers::VOffsetT = 4;
            pub const VT_CLIENT_TIME_MS: ::flatbuffers::VOffsetT = 6;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PlayerInput { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PlayerInputArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PlayerInput<'bldr>> {
                let mut builder = PlayerInputBuilder::new(_fbb);
                builder.add_client_time_ms(args.client_time_ms);
                if let Some(x) = args.transform {
                    builder.add_transform(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn transform(&self) -> Option<&'a Transform> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Transform>(PlayerInput::VT_TRANSFORM, None) }
            }
            #[inline]
            pub fn client_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(PlayerInput::VT_CLIENT_TIME_MS, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for PlayerInput<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<Transform>("transform", Self::VT_TRANSFORM, false)?
                    .visit_field::<u64>("client_time_ms", Self::VT_CLIENT_TIME_MS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PlayerInputArgs<'a> {
            pub transform: Option<&'a Transform>,
            pub client_time_ms: u64,
        }
        impl<'a> Default for PlayerInputArgs<'a> {
            #[inline]
            fn default() -> Self {
                PlayerInputArgs {
                    transform: None,
                    client_time_ms: 0,
                }
            }
        }

        pub struct PlayerInputBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerInputBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_transform(&mut self, transform: &Transform) {
                self.fbb_
                    .push_slot_always::<&Transform>(PlayerInput::VT_TRANSFORM, transform);
            }
            #[inline]
            pub fn add_client_time_ms(&mut self, client_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(PlayerInput::VT_CLIENT_TIME_MS, client_time_ms, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PlayerInputBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PlayerInputBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerInput<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PlayerInput<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PlayerInput");
                ds.field("transform", &self.transform());
                ds.field("client_time_ms", &self.client_time_ms());
                ds.finish()
            }
        }
        pub enum WorldSnapshotOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct WorldSnapshot<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for WorldSnapshot<'a> {
            type Inner = WorldSnapshot<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> WorldSnapshot<'a> {
            pub const VT_SERVER_TICK: ::flatbuffers::VOffsetT = 4;
            pub const VT_SERVER_TIME_MS: ::flatbuffers::VOffsetT = 6;
            pub const VT_PLAYERS: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                WorldSnapshot { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args WorldSnapshotArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<WorldSnapshot<'bldr>> {
                let mut builder = WorldSnapshotBuilder::new(_fbb);
                builder.add_server_time_ms(args.server_time_ms);
                builder.add_server_tick(args.server_tick);
                if let Some(x) = args.players {
                    builder.add_players(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn server_tick(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(WorldSnapshot::VT_SERVER_TICK, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn server_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(WorldSnapshot::VT_SERVER_TIME_MS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn players(&self) -> Option<::flatbuffers::Vector<'a, PlayerState>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, PlayerState>>>(WorldSnapshot::VT_PLAYERS, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for WorldSnapshot<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
     .visit_field::<u64>("server_tick", Self::VT_SERVER_TICK, false)?
     .visit_field::<u64>("server_time_ms", Self::VT_SERVER_TIME_MS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, PlayerState>>>("players", Self::VT_PLAYERS, false)?
     .finish();
                Ok(())
            }
        }
        pub struct WorldSnapshotArgs<'a> {
            pub server_tick: u64,
            pub server_time_ms: u64,
            pub players: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, PlayerState>>>,
        }
        impl<'a> Default for WorldSnapshotArgs<'a> {
            #[inline]
            fn default() -> Self {
                WorldSnapshotArgs {
                    server_tick: 0,
                    server_time_ms: 0,
                    players: None,
                }
            }
        }

        pub struct WorldSnapshotBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WorldSnapshotBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_server_tick(&mut self, server_tick: u64) {
                self.fbb_
                    .push_slot::<u64>(WorldSnapshot::VT_SERVER_TICK, server_tick, 0);
            }
            #[inline]
            pub fn add_server_time_ms(&mut self, server_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(WorldSnapshot::VT_SERVER_TIME_MS, server_time_ms, 0);
            }
            #[inline]
            pub fn add_players(
                &mut self,
                players: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, PlayerState>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    WorldSnapshot::VT_PLAYERS,
                    players,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> WorldSnapshotBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                WorldSnapshotBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<WorldSnapshot<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for WorldSnapshot<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("WorldSnapshot");
                ds.field("server_tick", &self.server_tick());
                ds.field("server_time_ms", &self.server_time_ms());
                ds.field("players", &self.players());
                ds.finish()
            }
        }
    } // pub mod v1
} // pub mod skyrim_relive
