#![allow(
    warnings,
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    clippy::cargo,
    clippy::style,
    clippy::complexity,
    clippy::correctness,
    clippy::perf,
    clippy::suspicious
)]
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod skyrim_relive {

    #[allow(unused_imports, dead_code)]
    pub mod v_1 {

        // struct Vec3, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct Vec3(pub [u8; 12]);
        impl Default for Vec3 {
            fn default() -> Self {
                Self([0; 12])
            }
        }
        impl ::core::fmt::Debug for Vec3 {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("Vec3")
                    .field("x", &self.x())
                    .field("y", &self.y())
                    .field("z", &self.z())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Vec3 {}
        impl<'a> ::flatbuffers::Follow<'a> for Vec3 {
            type Inner = &'a Vec3;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a Vec3>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a Vec3 {
            type Inner = &'a Vec3;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<Vec3>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for Vec3 {
            type Output = Vec3;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const Vec3 as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Vec3 {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> Vec3 {
            #[allow(clippy::too_many_arguments)]
            pub fn new(x: f32, y: f32, z: f32) -> Self {
                let mut s = Self([0; 12]);
                s.set_x(x);
                s.set_y(y);
                s.set_z(z);
                s
            }

            pub fn x(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_x(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn y(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_y(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn z(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_z(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct Transform, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct Transform(pub [u8; 16]);
        impl Default for Transform {
            fn default() -> Self {
                Self([0; 16])
            }
        }
        impl ::core::fmt::Debug for Transform {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("Transform")
                    .field("pos", &self.pos())
                    .field("yaw", &self.yaw())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Transform {}
        impl<'a> ::flatbuffers::Follow<'a> for Transform {
            type Inner = &'a Transform;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a Transform>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a Transform {
            type Inner = &'a Transform;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<Transform>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for Transform {
            type Output = Transform;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const Transform as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Transform {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> Transform {
            #[allow(clippy::too_many_arguments)]
            pub fn new(pos: &Vec3, yaw: f32) -> Self {
                let mut s = Self([0; 16]);
                s.set_pos(pos);
                s.set_yaw(yaw);
                s
            }

            pub fn pos(&self) -> &Vec3 {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid struct in this slot
                unsafe { &*(self.0[0..].as_ptr() as *const Vec3) }
            }

            #[allow(clippy::identity_op)]
            pub fn set_pos(&mut self, x: &Vec3) {
                self.0[0..0 + 12].copy_from_slice(&x.0)
            }

            pub fn yaw(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[12..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_yaw(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[12..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        pub enum PlayerStateOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct PlayerState<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PlayerState<'a> {
            type Inner = PlayerState<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> PlayerState<'a> {
            pub const VT_PLAYER_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_TRANSFORM: ::flatbuffers::VOffsetT = 6;
            pub const VT_ANIM_SPEED: ::flatbuffers::VOffsetT = 8;
            pub const VT_ANIM_DIRECTION: ::flatbuffers::VOffsetT = 10;
            pub const VT_ANIM_IS_RUNNING: ::flatbuffers::VOffsetT = 12;
            pub const VT_ANIM_IS_SPRINTING: ::flatbuffers::VOffsetT = 14;
            pub const VT_ANIM_IS_SNEAKING: ::flatbuffers::VOffsetT = 16;
            pub const VT_ANIM_IS_EQUIPPING: ::flatbuffers::VOffsetT = 18;
            pub const VT_ANIM_IS_UNEQUIPPING: ::flatbuffers::VOffsetT = 20;
            pub const VT_ANIM_WEAPON_STATE: ::flatbuffers::VOffsetT = 22;
            pub const VT_WEAPON_DRAWN: ::flatbuffers::VOffsetT = 24;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PlayerState { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PlayerStateArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PlayerState<'bldr>> {
                let mut builder = PlayerStateBuilder::new(_fbb);
                builder.add_anim_weapon_state(args.anim_weapon_state);
                builder.add_anim_direction(args.anim_direction);
                builder.add_anim_speed(args.anim_speed);
                if let Some(x) = args.transform {
                    builder.add_transform(x);
                }
                builder.add_player_id(args.player_id);
                builder.add_weapon_drawn(args.weapon_drawn);
                builder.add_anim_is_unequipping(args.anim_is_unequipping);
                builder.add_anim_is_equipping(args.anim_is_equipping);
                builder.add_anim_is_sneaking(args.anim_is_sneaking);
                builder.add_anim_is_sprinting(args.anim_is_sprinting);
                builder.add_anim_is_running(args.anim_is_running);
                builder.finish()
            }

            #[inline]
            pub fn player_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(PlayerState::VT_PLAYER_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn transform(&self) -> Option<&'a Transform> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Transform>(PlayerState::VT_TRANSFORM, None) }
            }
            #[inline]
            pub fn anim_speed(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerState::VT_ANIM_SPEED, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_direction(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerState::VT_ANIM_DIRECTION, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_running(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_RUNNING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sprinting(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_SPRINTING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sneaking(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_SNEAKING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_equipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_EQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_unequipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_UNEQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_weapon_state(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<i32>(PlayerState::VT_ANIM_WEAPON_STATE, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn weapon_drawn(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_WEAPON_DRAWN, Some(false))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for PlayerState<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("player_id", Self::VT_PLAYER_ID, false)?
                    .visit_field::<Transform>("transform", Self::VT_TRANSFORM, false)?
                    .visit_field::<f32>("anim_speed", Self::VT_ANIM_SPEED, false)?
                    .visit_field::<f32>("anim_direction", Self::VT_ANIM_DIRECTION, false)?
                    .visit_field::<bool>("anim_is_running", Self::VT_ANIM_IS_RUNNING, false)?
                    .visit_field::<bool>("anim_is_sprinting", Self::VT_ANIM_IS_SPRINTING, false)?
                    .visit_field::<bool>("anim_is_sneaking", Self::VT_ANIM_IS_SNEAKING, false)?
                    .visit_field::<bool>("anim_is_equipping", Self::VT_ANIM_IS_EQUIPPING, false)?
                    .visit_field::<bool>(
                        "anim_is_unequipping",
                        Self::VT_ANIM_IS_UNEQUIPPING,
                        false,
                    )?
                    .visit_field::<i32>("anim_weapon_state", Self::VT_ANIM_WEAPON_STATE, false)?
                    .visit_field::<bool>("weapon_drawn", Self::VT_WEAPON_DRAWN, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PlayerStateArgs<'a> {
            pub player_id: u32,
            pub transform: Option<&'a Transform>,
            pub anim_speed: f32,
            pub anim_direction: f32,
            pub anim_is_running: bool,
            pub anim_is_sprinting: bool,
            pub anim_is_sneaking: bool,
            pub anim_is_equipping: bool,
            pub anim_is_unequipping: bool,
            pub anim_weapon_state: i32,
            pub weapon_drawn: bool,
        }
        impl<'a> Default for PlayerStateArgs<'a> {
            #[inline]
            fn default() -> Self {
                PlayerStateArgs {
                    player_id: 0,
                    transform: None,
                    anim_speed: 0.0,
                    anim_direction: 0.0,
                    anim_is_running: false,
                    anim_is_sprinting: false,
                    anim_is_sneaking: false,
                    anim_is_equipping: false,
                    anim_is_unequipping: false,
                    anim_weapon_state: 0,
                    weapon_drawn: false,
                }
            }
        }

        pub struct PlayerStateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerStateBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_player_id(&mut self, player_id: u32) {
                self.fbb_
                    .push_slot::<u32>(PlayerState::VT_PLAYER_ID, player_id, 0);
            }
            #[inline]
            pub fn add_transform(&mut self, transform: &Transform) {
                self.fbb_
                    .push_slot_always::<&Transform>(PlayerState::VT_TRANSFORM, transform);
            }
            #[inline]
            pub fn add_anim_speed(&mut self, anim_speed: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerState::VT_ANIM_SPEED, anim_speed, 0.0);
            }
            #[inline]
            pub fn add_anim_direction(&mut self, anim_direction: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerState::VT_ANIM_DIRECTION, anim_direction, 0.0);
            }
            #[inline]
            pub fn add_anim_is_running(&mut self, anim_is_running: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_RUNNING,
                    anim_is_running,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sprinting(&mut self, anim_is_sprinting: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_SPRINTING,
                    anim_is_sprinting,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sneaking(&mut self, anim_is_sneaking: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_SNEAKING,
                    anim_is_sneaking,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_equipping(&mut self, anim_is_equipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_EQUIPPING,
                    anim_is_equipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_unequipping(&mut self, anim_is_unequipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_UNEQUIPPING,
                    anim_is_unequipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_weapon_state(&mut self, anim_weapon_state: i32) {
                self.fbb_
                    .push_slot::<i32>(PlayerState::VT_ANIM_WEAPON_STATE, anim_weapon_state, 0);
            }
            #[inline]
            pub fn add_weapon_drawn(&mut self, weapon_drawn: bool) {
                self.fbb_
                    .push_slot::<bool>(PlayerState::VT_WEAPON_DRAWN, weapon_drawn, false);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PlayerStateBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PlayerStateBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerState<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PlayerState<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PlayerState");
                ds.field("player_id", &self.player_id());
                ds.field("transform", &self.transform());
                ds.field("anim_speed", &self.anim_speed());
                ds.field("anim_direction", &self.anim_direction());
                ds.field("anim_is_running", &self.anim_is_running());
                ds.field("anim_is_sprinting", &self.anim_is_sprinting());
                ds.field("anim_is_sneaking", &self.anim_is_sneaking());
                ds.field("anim_is_equipping", &self.anim_is_equipping());
                ds.field("anim_is_unequipping", &self.anim_is_unequipping());
                ds.field("anim_weapon_state", &self.anim_weapon_state());
                ds.field("weapon_drawn", &self.weapon_drawn());
                ds.finish()
            }
        }
        pub enum PlayerInputOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct PlayerInput<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PlayerInput<'a> {
            type Inner = PlayerInput<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> PlayerInput<'a> {
            pub const VT_TRANSFORM: ::flatbuffers::VOffsetT = 4;
            pub const VT_CLIENT_TIME_MS: ::flatbuffers::VOffsetT = 6;
            pub const VT_ANIM_SPEED: ::flatbuffers::VOffsetT = 8;
            pub const VT_ANIM_DIRECTION: ::flatbuffers::VOffsetT = 10;
            pub const VT_ANIM_IS_RUNNING: ::flatbuffers::VOffsetT = 12;
            pub const VT_ANIM_IS_SPRINTING: ::flatbuffers::VOffsetT = 14;
            pub const VT_ANIM_IS_SNEAKING: ::flatbuffers::VOffsetT = 16;
            pub const VT_ANIM_IS_EQUIPPING: ::flatbuffers::VOffsetT = 18;
            pub const VT_ANIM_IS_UNEQUIPPING: ::flatbuffers::VOffsetT = 20;
            pub const VT_ANIM_WEAPON_STATE: ::flatbuffers::VOffsetT = 22;
            pub const VT_WEAPON_DRAWN: ::flatbuffers::VOffsetT = 24;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PlayerInput { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PlayerInputArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PlayerInput<'bldr>> {
                let mut builder = PlayerInputBuilder::new(_fbb);
                builder.add_client_time_ms(args.client_time_ms);
                builder.add_anim_weapon_state(args.anim_weapon_state);
                builder.add_anim_direction(args.anim_direction);
                builder.add_anim_speed(args.anim_speed);
                if let Some(x) = args.transform {
                    builder.add_transform(x);
                }
                builder.add_weapon_drawn(args.weapon_drawn);
                builder.add_anim_is_unequipping(args.anim_is_unequipping);
                builder.add_anim_is_equipping(args.anim_is_equipping);
                builder.add_anim_is_sneaking(args.anim_is_sneaking);
                builder.add_anim_is_sprinting(args.anim_is_sprinting);
                builder.add_anim_is_running(args.anim_is_running);
                builder.finish()
            }

            #[inline]
            pub fn transform(&self) -> Option<&'a Transform> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Transform>(PlayerInput::VT_TRANSFORM, None) }
            }
            #[inline]
            pub fn client_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(PlayerInput::VT_CLIENT_TIME_MS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_speed(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerInput::VT_ANIM_SPEED, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_direction(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerInput::VT_ANIM_DIRECTION, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_running(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_RUNNING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sprinting(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_SPRINTING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sneaking(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_SNEAKING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_equipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_EQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_unequipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_UNEQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_weapon_state(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<i32>(PlayerInput::VT_ANIM_WEAPON_STATE, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn weapon_drawn(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_WEAPON_DRAWN, Some(false))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for PlayerInput<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<Transform>("transform", Self::VT_TRANSFORM, false)?
                    .visit_field::<u64>("client_time_ms", Self::VT_CLIENT_TIME_MS, false)?
                    .visit_field::<f32>("anim_speed", Self::VT_ANIM_SPEED, false)?
                    .visit_field::<f32>("anim_direction", Self::VT_ANIM_DIRECTION, false)?
                    .visit_field::<bool>("anim_is_running", Self::VT_ANIM_IS_RUNNING, false)?
                    .visit_field::<bool>("anim_is_sprinting", Self::VT_ANIM_IS_SPRINTING, false)?
                    .visit_field::<bool>("anim_is_sneaking", Self::VT_ANIM_IS_SNEAKING, false)?
                    .visit_field::<bool>("anim_is_equipping", Self::VT_ANIM_IS_EQUIPPING, false)?
                    .visit_field::<bool>(
                        "anim_is_unequipping",
                        Self::VT_ANIM_IS_UNEQUIPPING,
                        false,
                    )?
                    .visit_field::<i32>("anim_weapon_state", Self::VT_ANIM_WEAPON_STATE, false)?
                    .visit_field::<bool>("weapon_drawn", Self::VT_WEAPON_DRAWN, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PlayerInputArgs<'a> {
            pub transform: Option<&'a Transform>,
            pub client_time_ms: u64,
            pub anim_speed: f32,
            pub anim_direction: f32,
            pub anim_is_running: bool,
            pub anim_is_sprinting: bool,
            pub anim_is_sneaking: bool,
            pub anim_is_equipping: bool,
            pub anim_is_unequipping: bool,
            pub anim_weapon_state: i32,
            pub weapon_drawn: bool,
        }
        impl<'a> Default for PlayerInputArgs<'a> {
            #[inline]
            fn default() -> Self {
                PlayerInputArgs {
                    transform: None,
                    client_time_ms: 0,
                    anim_speed: 0.0,
                    anim_direction: 0.0,
                    anim_is_running: false,
                    anim_is_sprinting: false,
                    anim_is_sneaking: false,
                    anim_is_equipping: false,
                    anim_is_unequipping: false,
                    anim_weapon_state: 0,
                    weapon_drawn: false,
                }
            }
        }

        pub struct PlayerInputBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerInputBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_transform(&mut self, transform: &Transform) {
                self.fbb_
                    .push_slot_always::<&Transform>(PlayerInput::VT_TRANSFORM, transform);
            }
            #[inline]
            pub fn add_client_time_ms(&mut self, client_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(PlayerInput::VT_CLIENT_TIME_MS, client_time_ms, 0);
            }
            #[inline]
            pub fn add_anim_speed(&mut self, anim_speed: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerInput::VT_ANIM_SPEED, anim_speed, 0.0);
            }
            #[inline]
            pub fn add_anim_direction(&mut self, anim_direction: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerInput::VT_ANIM_DIRECTION, anim_direction, 0.0);
            }
            #[inline]
            pub fn add_anim_is_running(&mut self, anim_is_running: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_RUNNING,
                    anim_is_running,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sprinting(&mut self, anim_is_sprinting: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_SPRINTING,
                    anim_is_sprinting,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sneaking(&mut self, anim_is_sneaking: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_SNEAKING,
                    anim_is_sneaking,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_equipping(&mut self, anim_is_equipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_EQUIPPING,
                    anim_is_equipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_unequipping(&mut self, anim_is_unequipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_UNEQUIPPING,
                    anim_is_unequipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_weapon_state(&mut self, anim_weapon_state: i32) {
                self.fbb_
                    .push_slot::<i32>(PlayerInput::VT_ANIM_WEAPON_STATE, anim_weapon_state, 0);
            }
            #[inline]
            pub fn add_weapon_drawn(&mut self, weapon_drawn: bool) {
                self.fbb_
                    .push_slot::<bool>(PlayerInput::VT_WEAPON_DRAWN, weapon_drawn, false);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PlayerInputBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PlayerInputBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerInput<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PlayerInput<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PlayerInput");
                ds.field("transform", &self.transform());
                ds.field("client_time_ms", &self.client_time_ms());
                ds.field("anim_speed", &self.anim_speed());
                ds.field("anim_direction", &self.anim_direction());
                ds.field("anim_is_running", &self.anim_is_running());
                ds.field("anim_is_sprinting", &self.anim_is_sprinting());
                ds.field("anim_is_sneaking", &self.anim_is_sneaking());
                ds.field("anim_is_equipping", &self.anim_is_equipping());
                ds.field("anim_is_unequipping", &self.anim_is_unequipping());
                ds.field("anim_weapon_state", &self.anim_weapon_state());
                ds.field("weapon_drawn", &self.weapon_drawn());
                ds.finish()
            }
        }
        pub enum WorldSnapshotOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct WorldSnapshot<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for WorldSnapshot<'a> {
            type Inner = WorldSnapshot<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> WorldSnapshot<'a> {
            pub const VT_SERVER_TICK: ::flatbuffers::VOffsetT = 4;
            pub const VT_SERVER_TIME_MS: ::flatbuffers::VOffsetT = 6;
            pub const VT_PLAYERS: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                WorldSnapshot { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args WorldSnapshotArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<WorldSnapshot<'bldr>> {
                let mut builder = WorldSnapshotBuilder::new(_fbb);
                builder.add_server_time_ms(args.server_time_ms);
                builder.add_server_tick(args.server_tick);
                if let Some(x) = args.players {
                    builder.add_players(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn server_tick(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(WorldSnapshot::VT_SERVER_TICK, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn server_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(WorldSnapshot::VT_SERVER_TIME_MS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn players(
                &self,
            ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerState<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerState>>,
                    >>(WorldSnapshot::VT_PLAYERS, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for WorldSnapshot<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("server_tick", Self::VT_SERVER_TICK, false)?
                    .visit_field::<u64>("server_time_ms", Self::VT_SERVER_TIME_MS, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<PlayerState>>,
                    >>("players", Self::VT_PLAYERS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct WorldSnapshotArgs<'a> {
            pub server_tick: u64,
            pub server_time_ms: u64,
            pub players: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerState<'a>>>,
                >,
            >,
        }
        impl<'a> Default for WorldSnapshotArgs<'a> {
            #[inline]
            fn default() -> Self {
                WorldSnapshotArgs {
                    server_tick: 0,
                    server_time_ms: 0,
                    players: None,
                }
            }
        }

        pub struct WorldSnapshotBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WorldSnapshotBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_server_tick(&mut self, server_tick: u64) {
                self.fbb_
                    .push_slot::<u64>(WorldSnapshot::VT_SERVER_TICK, server_tick, 0);
            }
            #[inline]
            pub fn add_server_time_ms(&mut self, server_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(WorldSnapshot::VT_SERVER_TIME_MS, server_time_ms, 0);
            }
            #[inline]
            pub fn add_players(
                &mut self,
                players: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<PlayerState<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    WorldSnapshot::VT_PLAYERS,
                    players,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> WorldSnapshotBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                WorldSnapshotBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<WorldSnapshot<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for WorldSnapshot<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("WorldSnapshot");
                ds.field("server_tick", &self.server_tick());
                ds.field("server_time_ms", &self.server_time_ms());
                ds.field("players", &self.players());
                ds.finish()
            }
        }
    } // pub mod v1
} // pub mod skyrim_relive
