#![allow(
    warnings,
    unsafe_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    clippy::cargo,
    clippy::style,
    clippy::complexity,
    clippy::correctness,
    clippy::perf,
    clippy::suspicious
)]
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

use crate::proto::v1::types_generated::skyrim_relive::v_1::*;

#[allow(unused_imports, dead_code)]
pub mod skyrim_relive {

    use crate::proto::v1::types_generated::skyrim_relive::v_1::*;
    #[allow(unused_imports, dead_code)]
    pub mod v_1 {

        use crate::proto::v1::types_generated::skyrim_relive::v_1::*;

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_ATTACK_CLASS: u8 = 0;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_ATTACK_CLASS: u8 = 2;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_ATTACK_CLASS: [AttackClass; 3] = [
            AttackClass::Melee,
            AttackClass::BowArrow,
            AttackClass::Spell,
        ];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct AttackClass(pub u8);
        #[allow(non_upper_case_globals)]
        impl AttackClass {
            pub const Melee: Self = Self(0);
            pub const BowArrow: Self = Self(1);
            pub const Spell: Self = Self(2);

            pub const ENUM_MIN: u8 = 0;
            pub const ENUM_MAX: u8 = 2;
            pub const ENUM_VALUES: &'static [Self] = &[Self::Melee, Self::BowArrow, Self::Spell];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::Melee => Some("Melee"),
                    Self::BowArrow => Some("BowArrow"),
                    Self::Spell => Some("Spell"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for AttackClass {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for AttackClass {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for AttackClass {
            type Output = AttackClass;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for AttackClass {
            type Scalar = u8;
            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for AttackClass {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for AttackClass {}
        // struct Vec3, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct Vec3(pub [u8; 12]);
        impl Default for Vec3 {
            fn default() -> Self {
                Self([0; 12])
            }
        }
        impl ::core::fmt::Debug for Vec3 {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("Vec3")
                    .field("x", &self.x())
                    .field("y", &self.y())
                    .field("z", &self.z())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Vec3 {}
        impl<'a> ::flatbuffers::Follow<'a> for Vec3 {
            type Inner = &'a Vec3;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a Vec3>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a Vec3 {
            type Inner = &'a Vec3;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<Vec3>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for Vec3 {
            type Output = Vec3;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const Vec3 as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Vec3 {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> Vec3 {
            #[allow(clippy::too_many_arguments)]
            pub fn new(x: f32, y: f32, z: f32) -> Self {
                let mut s = Self([0; 12]);
                s.set_x(x);
                s.set_y(y);
                s.set_z(z);
                s
            }

            pub fn x(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_x(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn y(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_y(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn z(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_z(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct Transform, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct Transform(pub [u8; 16]);
        impl Default for Transform {
            fn default() -> Self {
                Self([0; 16])
            }
        }
        impl ::core::fmt::Debug for Transform {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("Transform")
                    .field("pos", &self.pos())
                    .field("yaw", &self.yaw())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for Transform {}
        impl<'a> ::flatbuffers::Follow<'a> for Transform {
            type Inner = &'a Transform;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a Transform>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a Transform {
            type Inner = &'a Transform;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<Transform>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for Transform {
            type Output = Transform;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const Transform as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for Transform {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> Transform {
            #[allow(clippy::too_many_arguments)]
            pub fn new(pos: &Vec3, yaw: f32) -> Self {
                let mut s = Self([0; 16]);
                s.set_pos(pos);
                s.set_yaw(yaw);
                s
            }

            pub fn pos(&self) -> &Vec3 {
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid struct in this slot
                unsafe { &*(self.0[0..].as_ptr() as *const Vec3) }
            }

            #[allow(clippy::identity_op)]
            pub fn set_pos(&mut self, x: &Vec3) {
                self.0[0..0 + 12].copy_from_slice(&x.0)
            }

            pub fn yaw(&self) -> f32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <f32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[12..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_yaw(&mut self, x: f32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[12..].as_mut_ptr(),
                        ::core::mem::size_of::<<f32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        pub enum PlayerStateOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct PlayerState<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PlayerState<'a> {
            type Inner = PlayerState<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> PlayerState<'a> {
            pub const VT_PLAYER_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_TRANSFORM: ::flatbuffers::VOffsetT = 6;
            pub const VT_ANIM_SPEED: ::flatbuffers::VOffsetT = 8;
            pub const VT_ANIM_DIRECTION: ::flatbuffers::VOffsetT = 10;
            pub const VT_ANIM_IS_RUNNING: ::flatbuffers::VOffsetT = 12;
            pub const VT_ANIM_IS_SPRINTING: ::flatbuffers::VOffsetT = 14;
            pub const VT_ANIM_IS_SNEAKING: ::flatbuffers::VOffsetT = 16;
            pub const VT_ANIM_IS_EQUIPPING: ::flatbuffers::VOffsetT = 18;
            pub const VT_ANIM_IS_UNEQUIPPING: ::flatbuffers::VOffsetT = 20;
            pub const VT_ANIM_WEAPON_STATE: ::flatbuffers::VOffsetT = 22;
            pub const VT_WEAPON_DRAWN: ::flatbuffers::VOffsetT = 24;
            pub const VT_PITCH: ::flatbuffers::VOffsetT = 26;
            pub const VT_CELL_FORM_ID: ::flatbuffers::VOffsetT = 28;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PlayerState { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PlayerStateArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PlayerState<'bldr>> {
                let mut builder = PlayerStateBuilder::new(_fbb);
                builder.add_cell_form_id(args.cell_form_id);
                builder.add_pitch(args.pitch);
                builder.add_anim_weapon_state(args.anim_weapon_state);
                builder.add_anim_direction(args.anim_direction);
                builder.add_anim_speed(args.anim_speed);
                if let Some(x) = args.transform {
                    builder.add_transform(x);
                }
                builder.add_player_id(args.player_id);
                builder.add_weapon_drawn(args.weapon_drawn);
                builder.add_anim_is_unequipping(args.anim_is_unequipping);
                builder.add_anim_is_equipping(args.anim_is_equipping);
                builder.add_anim_is_sneaking(args.anim_is_sneaking);
                builder.add_anim_is_sprinting(args.anim_is_sprinting);
                builder.add_anim_is_running(args.anim_is_running);
                builder.finish()
            }

            #[inline]
            pub fn player_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(PlayerState::VT_PLAYER_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn transform(&self) -> Option<&'a Transform> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Transform>(PlayerState::VT_TRANSFORM, None) }
            }
            #[inline]
            pub fn anim_speed(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerState::VT_ANIM_SPEED, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_direction(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerState::VT_ANIM_DIRECTION, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_running(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_RUNNING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sprinting(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_SPRINTING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sneaking(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_SNEAKING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_equipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_EQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_unequipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_ANIM_IS_UNEQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_weapon_state(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<i32>(PlayerState::VT_ANIM_WEAPON_STATE, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn weapon_drawn(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerState::VT_WEAPON_DRAWN, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn pitch(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerState::VT_PITCH, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn cell_form_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(PlayerState::VT_CELL_FORM_ID, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for PlayerState<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("player_id", Self::VT_PLAYER_ID, false)?
                    .visit_field::<Transform>("transform", Self::VT_TRANSFORM, false)?
                    .visit_field::<f32>("anim_speed", Self::VT_ANIM_SPEED, false)?
                    .visit_field::<f32>("anim_direction", Self::VT_ANIM_DIRECTION, false)?
                    .visit_field::<bool>("anim_is_running", Self::VT_ANIM_IS_RUNNING, false)?
                    .visit_field::<bool>("anim_is_sprinting", Self::VT_ANIM_IS_SPRINTING, false)?
                    .visit_field::<bool>("anim_is_sneaking", Self::VT_ANIM_IS_SNEAKING, false)?
                    .visit_field::<bool>("anim_is_equipping", Self::VT_ANIM_IS_EQUIPPING, false)?
                    .visit_field::<bool>(
                        "anim_is_unequipping",
                        Self::VT_ANIM_IS_UNEQUIPPING,
                        false,
                    )?
                    .visit_field::<i32>("anim_weapon_state", Self::VT_ANIM_WEAPON_STATE, false)?
                    .visit_field::<bool>("weapon_drawn", Self::VT_WEAPON_DRAWN, false)?
                    .visit_field::<f32>("pitch", Self::VT_PITCH, false)?
                    .visit_field::<u32>("cell_form_id", Self::VT_CELL_FORM_ID, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PlayerStateArgs<'a> {
            pub player_id: u32,
            pub transform: Option<&'a Transform>,
            pub anim_speed: f32,
            pub anim_direction: f32,
            pub anim_is_running: bool,
            pub anim_is_sprinting: bool,
            pub anim_is_sneaking: bool,
            pub anim_is_equipping: bool,
            pub anim_is_unequipping: bool,
            pub anim_weapon_state: i32,
            pub weapon_drawn: bool,
            pub pitch: f32,
            pub cell_form_id: u32,
        }
        impl<'a> Default for PlayerStateArgs<'a> {
            #[inline]
            fn default() -> Self {
                PlayerStateArgs {
                    player_id: 0,
                    transform: None,
                    anim_speed: 0.0,
                    anim_direction: 0.0,
                    anim_is_running: false,
                    anim_is_sprinting: false,
                    anim_is_sneaking: false,
                    anim_is_equipping: false,
                    anim_is_unequipping: false,
                    anim_weapon_state: 0,
                    weapon_drawn: false,
                    pitch: 0.0,
                    cell_form_id: 0,
                }
            }
        }

        pub struct PlayerStateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerStateBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_player_id(&mut self, player_id: u32) {
                self.fbb_
                    .push_slot::<u32>(PlayerState::VT_PLAYER_ID, player_id, 0);
            }
            #[inline]
            pub fn add_transform(&mut self, transform: &Transform) {
                self.fbb_
                    .push_slot_always::<&Transform>(PlayerState::VT_TRANSFORM, transform);
            }
            #[inline]
            pub fn add_anim_speed(&mut self, anim_speed: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerState::VT_ANIM_SPEED, anim_speed, 0.0);
            }
            #[inline]
            pub fn add_anim_direction(&mut self, anim_direction: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerState::VT_ANIM_DIRECTION, anim_direction, 0.0);
            }
            #[inline]
            pub fn add_anim_is_running(&mut self, anim_is_running: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_RUNNING,
                    anim_is_running,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sprinting(&mut self, anim_is_sprinting: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_SPRINTING,
                    anim_is_sprinting,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sneaking(&mut self, anim_is_sneaking: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_SNEAKING,
                    anim_is_sneaking,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_equipping(&mut self, anim_is_equipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_EQUIPPING,
                    anim_is_equipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_unequipping(&mut self, anim_is_unequipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerState::VT_ANIM_IS_UNEQUIPPING,
                    anim_is_unequipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_weapon_state(&mut self, anim_weapon_state: i32) {
                self.fbb_
                    .push_slot::<i32>(PlayerState::VT_ANIM_WEAPON_STATE, anim_weapon_state, 0);
            }
            #[inline]
            pub fn add_weapon_drawn(&mut self, weapon_drawn: bool) {
                self.fbb_
                    .push_slot::<bool>(PlayerState::VT_WEAPON_DRAWN, weapon_drawn, false);
            }
            #[inline]
            pub fn add_pitch(&mut self, pitch: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerState::VT_PITCH, pitch, 0.0);
            }
            #[inline]
            pub fn add_cell_form_id(&mut self, cell_form_id: u32) {
                self.fbb_
                    .push_slot::<u32>(PlayerState::VT_CELL_FORM_ID, cell_form_id, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PlayerStateBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PlayerStateBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerState<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PlayerState<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PlayerState");
                ds.field("player_id", &self.player_id());
                ds.field("transform", &self.transform());
                ds.field("anim_speed", &self.anim_speed());
                ds.field("anim_direction", &self.anim_direction());
                ds.field("anim_is_running", &self.anim_is_running());
                ds.field("anim_is_sprinting", &self.anim_is_sprinting());
                ds.field("anim_is_sneaking", &self.anim_is_sneaking());
                ds.field("anim_is_equipping", &self.anim_is_equipping());
                ds.field("anim_is_unequipping", &self.anim_is_unequipping());
                ds.field("anim_weapon_state", &self.anim_weapon_state());
                ds.field("weapon_drawn", &self.weapon_drawn());
                ds.field("pitch", &self.pitch());
                ds.field("cell_form_id", &self.cell_form_id());
                ds.finish()
            }
        }
        pub enum PlayerInputOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct PlayerInput<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PlayerInput<'a> {
            type Inner = PlayerInput<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> PlayerInput<'a> {
            pub const VT_TRANSFORM: ::flatbuffers::VOffsetT = 4;
            pub const VT_CLIENT_TIME_MS: ::flatbuffers::VOffsetT = 6;
            pub const VT_ANIM_SPEED: ::flatbuffers::VOffsetT = 8;
            pub const VT_ANIM_DIRECTION: ::flatbuffers::VOffsetT = 10;
            pub const VT_ANIM_IS_RUNNING: ::flatbuffers::VOffsetT = 12;
            pub const VT_ANIM_IS_SPRINTING: ::flatbuffers::VOffsetT = 14;
            pub const VT_ANIM_IS_SNEAKING: ::flatbuffers::VOffsetT = 16;
            pub const VT_ANIM_IS_EQUIPPING: ::flatbuffers::VOffsetT = 18;
            pub const VT_ANIM_IS_UNEQUIPPING: ::flatbuffers::VOffsetT = 20;
            pub const VT_ANIM_WEAPON_STATE: ::flatbuffers::VOffsetT = 22;
            pub const VT_WEAPON_DRAWN: ::flatbuffers::VOffsetT = 24;
            pub const VT_PITCH: ::flatbuffers::VOffsetT = 26;
            pub const VT_CELL_FORM_ID: ::flatbuffers::VOffsetT = 28;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PlayerInput { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PlayerInputArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PlayerInput<'bldr>> {
                let mut builder = PlayerInputBuilder::new(_fbb);
                builder.add_client_time_ms(args.client_time_ms);
                builder.add_cell_form_id(args.cell_form_id);
                builder.add_pitch(args.pitch);
                builder.add_anim_weapon_state(args.anim_weapon_state);
                builder.add_anim_direction(args.anim_direction);
                builder.add_anim_speed(args.anim_speed);
                if let Some(x) = args.transform {
                    builder.add_transform(x);
                }
                builder.add_weapon_drawn(args.weapon_drawn);
                builder.add_anim_is_unequipping(args.anim_is_unequipping);
                builder.add_anim_is_equipping(args.anim_is_equipping);
                builder.add_anim_is_sneaking(args.anim_is_sneaking);
                builder.add_anim_is_sprinting(args.anim_is_sprinting);
                builder.add_anim_is_running(args.anim_is_running);
                builder.finish()
            }

            #[inline]
            pub fn transform(&self) -> Option<&'a Transform> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Transform>(PlayerInput::VT_TRANSFORM, None) }
            }
            #[inline]
            pub fn client_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(PlayerInput::VT_CLIENT_TIME_MS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_speed(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerInput::VT_ANIM_SPEED, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_direction(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerInput::VT_ANIM_DIRECTION, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_running(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_RUNNING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sprinting(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_SPRINTING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_sneaking(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_SNEAKING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_equipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_EQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_is_unequipping(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_ANIM_IS_UNEQUIPPING, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn anim_weapon_state(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<i32>(PlayerInput::VT_ANIM_WEAPON_STATE, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn weapon_drawn(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(PlayerInput::VT_WEAPON_DRAWN, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn pitch(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerInput::VT_PITCH, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn cell_form_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(PlayerInput::VT_CELL_FORM_ID, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for PlayerInput<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<Transform>("transform", Self::VT_TRANSFORM, false)?
                    .visit_field::<u64>("client_time_ms", Self::VT_CLIENT_TIME_MS, false)?
                    .visit_field::<f32>("anim_speed", Self::VT_ANIM_SPEED, false)?
                    .visit_field::<f32>("anim_direction", Self::VT_ANIM_DIRECTION, false)?
                    .visit_field::<bool>("anim_is_running", Self::VT_ANIM_IS_RUNNING, false)?
                    .visit_field::<bool>("anim_is_sprinting", Self::VT_ANIM_IS_SPRINTING, false)?
                    .visit_field::<bool>("anim_is_sneaking", Self::VT_ANIM_IS_SNEAKING, false)?
                    .visit_field::<bool>("anim_is_equipping", Self::VT_ANIM_IS_EQUIPPING, false)?
                    .visit_field::<bool>(
                        "anim_is_unequipping",
                        Self::VT_ANIM_IS_UNEQUIPPING,
                        false,
                    )?
                    .visit_field::<i32>("anim_weapon_state", Self::VT_ANIM_WEAPON_STATE, false)?
                    .visit_field::<bool>("weapon_drawn", Self::VT_WEAPON_DRAWN, false)?
                    .visit_field::<f32>("pitch", Self::VT_PITCH, false)?
                    .visit_field::<u32>("cell_form_id", Self::VT_CELL_FORM_ID, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PlayerInputArgs<'a> {
            pub transform: Option<&'a Transform>,
            pub client_time_ms: u64,
            pub anim_speed: f32,
            pub anim_direction: f32,
            pub anim_is_running: bool,
            pub anim_is_sprinting: bool,
            pub anim_is_sneaking: bool,
            pub anim_is_equipping: bool,
            pub anim_is_unequipping: bool,
            pub anim_weapon_state: i32,
            pub weapon_drawn: bool,
            pub pitch: f32,
            pub cell_form_id: u32,
        }
        impl<'a> Default for PlayerInputArgs<'a> {
            #[inline]
            fn default() -> Self {
                PlayerInputArgs {
                    transform: None,
                    client_time_ms: 0,
                    anim_speed: 0.0,
                    anim_direction: 0.0,
                    anim_is_running: false,
                    anim_is_sprinting: false,
                    anim_is_sneaking: false,
                    anim_is_equipping: false,
                    anim_is_unequipping: false,
                    anim_weapon_state: 0,
                    weapon_drawn: false,
                    pitch: 0.0,
                    cell_form_id: 0,
                }
            }
        }

        pub struct PlayerInputBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerInputBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_transform(&mut self, transform: &Transform) {
                self.fbb_
                    .push_slot_always::<&Transform>(PlayerInput::VT_TRANSFORM, transform);
            }
            #[inline]
            pub fn add_client_time_ms(&mut self, client_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(PlayerInput::VT_CLIENT_TIME_MS, client_time_ms, 0);
            }
            #[inline]
            pub fn add_anim_speed(&mut self, anim_speed: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerInput::VT_ANIM_SPEED, anim_speed, 0.0);
            }
            #[inline]
            pub fn add_anim_direction(&mut self, anim_direction: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerInput::VT_ANIM_DIRECTION, anim_direction, 0.0);
            }
            #[inline]
            pub fn add_anim_is_running(&mut self, anim_is_running: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_RUNNING,
                    anim_is_running,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sprinting(&mut self, anim_is_sprinting: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_SPRINTING,
                    anim_is_sprinting,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_sneaking(&mut self, anim_is_sneaking: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_SNEAKING,
                    anim_is_sneaking,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_equipping(&mut self, anim_is_equipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_EQUIPPING,
                    anim_is_equipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_is_unequipping(&mut self, anim_is_unequipping: bool) {
                self.fbb_.push_slot::<bool>(
                    PlayerInput::VT_ANIM_IS_UNEQUIPPING,
                    anim_is_unequipping,
                    false,
                );
            }
            #[inline]
            pub fn add_anim_weapon_state(&mut self, anim_weapon_state: i32) {
                self.fbb_
                    .push_slot::<i32>(PlayerInput::VT_ANIM_WEAPON_STATE, anim_weapon_state, 0);
            }
            #[inline]
            pub fn add_weapon_drawn(&mut self, weapon_drawn: bool) {
                self.fbb_
                    .push_slot::<bool>(PlayerInput::VT_WEAPON_DRAWN, weapon_drawn, false);
            }
            #[inline]
            pub fn add_pitch(&mut self, pitch: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerInput::VT_PITCH, pitch, 0.0);
            }
            #[inline]
            pub fn add_cell_form_id(&mut self, cell_form_id: u32) {
                self.fbb_
                    .push_slot::<u32>(PlayerInput::VT_CELL_FORM_ID, cell_form_id, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PlayerInputBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PlayerInputBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerInput<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PlayerInput<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PlayerInput");
                ds.field("transform", &self.transform());
                ds.field("client_time_ms", &self.client_time_ms());
                ds.field("anim_speed", &self.anim_speed());
                ds.field("anim_direction", &self.anim_direction());
                ds.field("anim_is_running", &self.anim_is_running());
                ds.field("anim_is_sprinting", &self.anim_is_sprinting());
                ds.field("anim_is_sneaking", &self.anim_is_sneaking());
                ds.field("anim_is_equipping", &self.anim_is_equipping());
                ds.field("anim_is_unequipping", &self.anim_is_unequipping());
                ds.field("anim_weapon_state", &self.anim_weapon_state());
                ds.field("weapon_drawn", &self.weapon_drawn());
                ds.field("pitch", &self.pitch());
                ds.field("cell_form_id", &self.cell_form_id());
                ds.finish()
            }
        }
        pub enum WorldSnapshotOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct WorldSnapshot<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for WorldSnapshot<'a> {
            type Inner = WorldSnapshot<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> WorldSnapshot<'a> {
            pub const VT_SERVER_TICK: ::flatbuffers::VOffsetT = 4;
            pub const VT_SERVER_TIME_MS: ::flatbuffers::VOffsetT = 6;
            pub const VT_PLAYERS: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                WorldSnapshot { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args WorldSnapshotArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<WorldSnapshot<'bldr>> {
                let mut builder = WorldSnapshotBuilder::new(_fbb);
                builder.add_server_time_ms(args.server_time_ms);
                builder.add_server_tick(args.server_tick);
                if let Some(x) = args.players {
                    builder.add_players(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn server_tick(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(WorldSnapshot::VT_SERVER_TICK, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn server_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(WorldSnapshot::VT_SERVER_TIME_MS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn players(
                &self,
            ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerState<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerState>>,
                    >>(WorldSnapshot::VT_PLAYERS, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for WorldSnapshot<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("server_tick", Self::VT_SERVER_TICK, false)?
                    .visit_field::<u64>("server_time_ms", Self::VT_SERVER_TIME_MS, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<PlayerState>>,
                    >>("players", Self::VT_PLAYERS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct WorldSnapshotArgs<'a> {
            pub server_tick: u64,
            pub server_time_ms: u64,
            pub players: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerState<'a>>>,
                >,
            >,
        }
        impl<'a> Default for WorldSnapshotArgs<'a> {
            #[inline]
            fn default() -> Self {
                WorldSnapshotArgs {
                    server_tick: 0,
                    server_time_ms: 0,
                    players: None,
                }
            }
        }

        pub struct WorldSnapshotBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WorldSnapshotBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_server_tick(&mut self, server_tick: u64) {
                self.fbb_
                    .push_slot::<u64>(WorldSnapshot::VT_SERVER_TICK, server_tick, 0);
            }
            #[inline]
            pub fn add_server_time_ms(&mut self, server_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(WorldSnapshot::VT_SERVER_TIME_MS, server_time_ms, 0);
            }
            #[inline]
            pub fn add_players(
                &mut self,
                players: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<PlayerState<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    WorldSnapshot::VT_PLAYERS,
                    players,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> WorldSnapshotBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                WorldSnapshotBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<WorldSnapshot<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for WorldSnapshot<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("WorldSnapshot");
                ds.field("server_tick", &self.server_tick());
                ds.field("server_time_ms", &self.server_time_ms());
                ds.field("players", &self.players());
                ds.finish()
            }
        }
        pub enum PlayerListEntryOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct PlayerListEntry<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PlayerListEntry<'a> {
            type Inner = PlayerListEntry<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> PlayerListEntry<'a> {
            pub const VT_PLAYER_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_DISPLAY_NAME: ::flatbuffers::VOffsetT = 6;
            pub const VT_CHARACTER_NAME: ::flatbuffers::VOffsetT = 8;
            pub const VT_CHARACTER_LEVEL: ::flatbuffers::VOffsetT = 10;
            pub const VT_TOP_SKILLS: ::flatbuffers::VOffsetT = 12;
            pub const VT_POS: ::flatbuffers::VOffsetT = 14;
            pub const VT_CELL_FORM_ID: ::flatbuffers::VOffsetT = 16;
            pub const VT_HP: ::flatbuffers::VOffsetT = 18;
            pub const VT_HP_MAX: ::flatbuffers::VOffsetT = 20;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PlayerListEntry { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PlayerListEntryArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PlayerListEntry<'bldr>> {
                let mut builder = PlayerListEntryBuilder::new(_fbb);
                builder.add_hp_max(args.hp_max);
                builder.add_hp(args.hp);
                builder.add_cell_form_id(args.cell_form_id);
                if let Some(x) = args.pos {
                    builder.add_pos(x);
                }
                if let Some(x) = args.top_skills {
                    builder.add_top_skills(x);
                }
                if let Some(x) = args.character_name {
                    builder.add_character_name(x);
                }
                if let Some(x) = args.display_name {
                    builder.add_display_name(x);
                }
                builder.add_player_id(args.player_id);
                builder.add_character_level(args.character_level);
                builder.finish()
            }

            #[inline]
            pub fn player_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(PlayerListEntry::VT_PLAYER_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn display_name(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                        PlayerListEntry::VT_DISPLAY_NAME,
                        None,
                    )
                }
            }
            #[inline]
            pub fn character_name(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                        PlayerListEntry::VT_CHARACTER_NAME,
                        None,
                    )
                }
            }
            #[inline]
            pub fn character_level(&self) -> u16 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u16>(PlayerListEntry::VT_CHARACTER_LEVEL, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn top_skills(
                &self,
            ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<SkillEntry<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<SkillEntry>>,
                    >>(PlayerListEntry::VT_TOP_SKILLS, None)
                }
            }
            #[inline]
            pub fn pos(&self) -> Option<&'a Vec3> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<Vec3>(PlayerListEntry::VT_POS, None) }
            }
            #[inline]
            pub fn cell_form_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(PlayerListEntry::VT_CELL_FORM_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn hp(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerListEntry::VT_HP, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn hp_max(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(PlayerListEntry::VT_HP_MAX, Some(0.0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for PlayerListEntry<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("player_id", Self::VT_PLAYER_ID, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "display_name",
                        Self::VT_DISPLAY_NAME,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "character_name",
                        Self::VT_CHARACTER_NAME,
                        false,
                    )?
                    .visit_field::<u16>("character_level", Self::VT_CHARACTER_LEVEL, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<SkillEntry>>,
                    >>("top_skills", Self::VT_TOP_SKILLS, false)?
                    .visit_field::<Vec3>("pos", Self::VT_POS, false)?
                    .visit_field::<u32>("cell_form_id", Self::VT_CELL_FORM_ID, false)?
                    .visit_field::<f32>("hp", Self::VT_HP, false)?
                    .visit_field::<f32>("hp_max", Self::VT_HP_MAX, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PlayerListEntryArgs<'a> {
            pub player_id: u32,
            pub display_name: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub character_name: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub character_level: u16,
            pub top_skills: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<SkillEntry<'a>>>,
                >,
            >,
            pub pos: Option<&'a Vec3>,
            pub cell_form_id: u32,
            pub hp: f32,
            pub hp_max: f32,
        }
        impl<'a> Default for PlayerListEntryArgs<'a> {
            #[inline]
            fn default() -> Self {
                PlayerListEntryArgs {
                    player_id: 0,
                    display_name: None,
                    character_name: None,
                    character_level: 0,
                    top_skills: None,
                    pos: None,
                    cell_form_id: 0,
                    hp: 0.0,
                    hp_max: 0.0,
                }
            }
        }

        pub struct PlayerListEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerListEntryBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_player_id(&mut self, player_id: u32) {
                self.fbb_
                    .push_slot::<u32>(PlayerListEntry::VT_PLAYER_ID, player_id, 0);
            }
            #[inline]
            pub fn add_display_name(&mut self, display_name: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    PlayerListEntry::VT_DISPLAY_NAME,
                    display_name,
                );
            }
            #[inline]
            pub fn add_character_name(
                &mut self,
                character_name: ::flatbuffers::WIPOffset<&'b str>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    PlayerListEntry::VT_CHARACTER_NAME,
                    character_name,
                );
            }
            #[inline]
            pub fn add_character_level(&mut self, character_level: u16) {
                self.fbb_
                    .push_slot::<u16>(PlayerListEntry::VT_CHARACTER_LEVEL, character_level, 0);
            }
            #[inline]
            pub fn add_top_skills(
                &mut self,
                top_skills: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<SkillEntry<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    PlayerListEntry::VT_TOP_SKILLS,
                    top_skills,
                );
            }
            #[inline]
            pub fn add_pos(&mut self, pos: &Vec3) {
                self.fbb_
                    .push_slot_always::<&Vec3>(PlayerListEntry::VT_POS, pos);
            }
            #[inline]
            pub fn add_cell_form_id(&mut self, cell_form_id: u32) {
                self.fbb_
                    .push_slot::<u32>(PlayerListEntry::VT_CELL_FORM_ID, cell_form_id, 0);
            }
            #[inline]
            pub fn add_hp(&mut self, hp: f32) {
                self.fbb_.push_slot::<f32>(PlayerListEntry::VT_HP, hp, 0.0);
            }
            #[inline]
            pub fn add_hp_max(&mut self, hp_max: f32) {
                self.fbb_
                    .push_slot::<f32>(PlayerListEntry::VT_HP_MAX, hp_max, 0.0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PlayerListEntryBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PlayerListEntryBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerListEntry<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PlayerListEntry<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PlayerListEntry");
                ds.field("player_id", &self.player_id());
                ds.field("display_name", &self.display_name());
                ds.field("character_name", &self.character_name());
                ds.field("character_level", &self.character_level());
                ds.field("top_skills", &self.top_skills());
                ds.field("pos", &self.pos());
                ds.field("cell_form_id", &self.cell_form_id());
                ds.field("hp", &self.hp());
                ds.field("hp_max", &self.hp_max());
                ds.finish()
            }
        }
        pub enum PlayerListOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct PlayerList<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PlayerList<'a> {
            type Inner = PlayerList<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> PlayerList<'a> {
            pub const VT_SERVER_TIME_MS: ::flatbuffers::VOffsetT = 4;
            pub const VT_PLAYERS: ::flatbuffers::VOffsetT = 6;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PlayerList { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PlayerListArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PlayerList<'bldr>> {
                let mut builder = PlayerListBuilder::new(_fbb);
                builder.add_server_time_ms(args.server_time_ms);
                if let Some(x) = args.players {
                    builder.add_players(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn server_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(PlayerList::VT_SERVER_TIME_MS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn players(
                &self,
            ) -> Option<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerListEntry<'a>>>,
            > {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerListEntry>>,
                    >>(PlayerList::VT_PLAYERS, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for PlayerList<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("server_time_ms", Self::VT_SERVER_TIME_MS, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<PlayerListEntry>>,
                    >>("players", Self::VT_PLAYERS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PlayerListArgs<'a> {
            pub server_time_ms: u64,
            pub players: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PlayerListEntry<'a>>>,
                >,
            >,
        }
        impl<'a> Default for PlayerListArgs<'a> {
            #[inline]
            fn default() -> Self {
                PlayerListArgs {
                    server_time_ms: 0,
                    players: None,
                }
            }
        }

        pub struct PlayerListBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlayerListBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_server_time_ms(&mut self, server_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(PlayerList::VT_SERVER_TIME_MS, server_time_ms, 0);
            }
            #[inline]
            pub fn add_players(
                &mut self,
                players: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<PlayerListEntry<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    PlayerList::VT_PLAYERS,
                    players,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PlayerListBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PlayerListBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PlayerList<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PlayerList<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PlayerList");
                ds.field("server_time_ms", &self.server_time_ms());
                ds.field("players", &self.players());
                ds.finish()
            }
        }
        pub enum CombatEventOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct CombatEvent<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for CombatEvent<'a> {
            type Inner = CombatEvent<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> CombatEvent<'a> {
            pub const VT_TARGET_PLAYER_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_ATTACK_TYPE: ::flatbuffers::VOffsetT = 6;
            pub const VT_WEAPON_REACH: ::flatbuffers::VOffsetT = 8;
            pub const VT_WEAPON_BASE_DAMAGE: ::flatbuffers::VOffsetT = 10;
            pub const VT_CLIENT_TIME_MS: ::flatbuffers::VOffsetT = 12;
            pub const VT_ATTACK_CLASS: ::flatbuffers::VOffsetT = 14;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                CombatEvent { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args CombatEventArgs,
            ) -> ::flatbuffers::WIPOffset<CombatEvent<'bldr>> {
                let mut builder = CombatEventBuilder::new(_fbb);
                builder.add_client_time_ms(args.client_time_ms);
                builder.add_weapon_base_damage(args.weapon_base_damage);
                builder.add_weapon_reach(args.weapon_reach);
                builder.add_target_player_id(args.target_player_id);
                builder.add_attack_class(args.attack_class);
                builder.add_attack_type(args.attack_type);
                builder.finish()
            }

            #[inline]
            pub fn target_player_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(CombatEvent::VT_TARGET_PLAYER_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn attack_type(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u8>(CombatEvent::VT_ATTACK_TYPE, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn weapon_reach(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(CombatEvent::VT_WEAPON_REACH, Some(100.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn weapon_base_damage(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(CombatEvent::VT_WEAPON_BASE_DAMAGE, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn client_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(CombatEvent::VT_CLIENT_TIME_MS, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn attack_class(&self) -> AttackClass {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<AttackClass>(CombatEvent::VT_ATTACK_CLASS, Some(AttackClass::Melee))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for CombatEvent<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("target_player_id", Self::VT_TARGET_PLAYER_ID, false)?
                    .visit_field::<u8>("attack_type", Self::VT_ATTACK_TYPE, false)?
                    .visit_field::<f32>("weapon_reach", Self::VT_WEAPON_REACH, false)?
                    .visit_field::<f32>("weapon_base_damage", Self::VT_WEAPON_BASE_DAMAGE, false)?
                    .visit_field::<u64>("client_time_ms", Self::VT_CLIENT_TIME_MS, false)?
                    .visit_field::<AttackClass>("attack_class", Self::VT_ATTACK_CLASS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct CombatEventArgs {
            pub target_player_id: u32,
            pub attack_type: u8,
            pub weapon_reach: f32,
            pub weapon_base_damage: f32,
            pub client_time_ms: u64,
            pub attack_class: AttackClass,
        }
        impl<'a> Default for CombatEventArgs {
            #[inline]
            fn default() -> Self {
                CombatEventArgs {
                    target_player_id: 0,
                    attack_type: 0,
                    weapon_reach: 100.0,
                    weapon_base_damage: 0.0,
                    client_time_ms: 0,
                    attack_class: AttackClass::Melee,
                }
            }
        }

        pub struct CombatEventBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CombatEventBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_target_player_id(&mut self, target_player_id: u32) {
                self.fbb_
                    .push_slot::<u32>(CombatEvent::VT_TARGET_PLAYER_ID, target_player_id, 0);
            }
            #[inline]
            pub fn add_attack_type(&mut self, attack_type: u8) {
                self.fbb_
                    .push_slot::<u8>(CombatEvent::VT_ATTACK_TYPE, attack_type, 0);
            }
            #[inline]
            pub fn add_weapon_reach(&mut self, weapon_reach: f32) {
                self.fbb_
                    .push_slot::<f32>(CombatEvent::VT_WEAPON_REACH, weapon_reach, 100.0);
            }
            #[inline]
            pub fn add_weapon_base_damage(&mut self, weapon_base_damage: f32) {
                self.fbb_.push_slot::<f32>(
                    CombatEvent::VT_WEAPON_BASE_DAMAGE,
                    weapon_base_damage,
                    0.0,
                );
            }
            #[inline]
            pub fn add_client_time_ms(&mut self, client_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(CombatEvent::VT_CLIENT_TIME_MS, client_time_ms, 0);
            }
            #[inline]
            pub fn add_attack_class(&mut self, attack_class: AttackClass) {
                self.fbb_.push_slot::<AttackClass>(
                    CombatEvent::VT_ATTACK_CLASS,
                    attack_class,
                    AttackClass::Melee,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> CombatEventBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                CombatEventBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<CombatEvent<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for CombatEvent<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("CombatEvent");
                ds.field("target_player_id", &self.target_player_id());
                ds.field("attack_type", &self.attack_type());
                ds.field("weapon_reach", &self.weapon_reach());
                ds.field("weapon_base_damage", &self.weapon_base_damage());
                ds.field("client_time_ms", &self.client_time_ms());
                ds.field("attack_class", &self.attack_class());
                ds.finish()
            }
        }
        pub enum DamageApplyOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct DamageApply<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for DamageApply<'a> {
            type Inner = DamageApply<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> DamageApply<'a> {
            pub const VT_ATTACKER_PLAYER_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_DAMAGE: ::flatbuffers::VOffsetT = 6;
            pub const VT_STAGGER: ::flatbuffers::VOffsetT = 8;
            pub const VT_NEW_HP: ::flatbuffers::VOffsetT = 10;
            pub const VT_SERVER_TIME_MS: ::flatbuffers::VOffsetT = 12;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                DamageApply { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args DamageApplyArgs,
            ) -> ::flatbuffers::WIPOffset<DamageApply<'bldr>> {
                let mut builder = DamageApplyBuilder::new(_fbb);
                builder.add_server_time_ms(args.server_time_ms);
                builder.add_new_hp(args.new_hp);
                builder.add_damage(args.damage);
                builder.add_attacker_player_id(args.attacker_player_id);
                builder.add_stagger(args.stagger);
                builder.finish()
            }

            #[inline]
            pub fn attacker_player_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u32>(DamageApply::VT_ATTACKER_PLAYER_ID, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn damage(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(DamageApply::VT_DAMAGE, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn stagger(&self) -> bool {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<bool>(DamageApply::VT_STAGGER, Some(false))
                        .unwrap()
                }
            }
            #[inline]
            pub fn new_hp(&self) -> f32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<f32>(DamageApply::VT_NEW_HP, Some(0.0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn server_time_ms(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(DamageApply::VT_SERVER_TIME_MS, Some(0))
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for DamageApply<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("attacker_player_id", Self::VT_ATTACKER_PLAYER_ID, false)?
                    .visit_field::<f32>("damage", Self::VT_DAMAGE, false)?
                    .visit_field::<bool>("stagger", Self::VT_STAGGER, false)?
                    .visit_field::<f32>("new_hp", Self::VT_NEW_HP, false)?
                    .visit_field::<u64>("server_time_ms", Self::VT_SERVER_TIME_MS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct DamageApplyArgs {
            pub attacker_player_id: u32,
            pub damage: f32,
            pub stagger: bool,
            pub new_hp: f32,
            pub server_time_ms: u64,
        }
        impl<'a> Default for DamageApplyArgs {
            #[inline]
            fn default() -> Self {
                DamageApplyArgs {
                    attacker_player_id: 0,
                    damage: 0.0,
                    stagger: false,
                    new_hp: 0.0,
                    server_time_ms: 0,
                }
            }
        }

        pub struct DamageApplyBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DamageApplyBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_attacker_player_id(&mut self, attacker_player_id: u32) {
                self.fbb_.push_slot::<u32>(
                    DamageApply::VT_ATTACKER_PLAYER_ID,
                    attacker_player_id,
                    0,
                );
            }
            #[inline]
            pub fn add_damage(&mut self, damage: f32) {
                self.fbb_
                    .push_slot::<f32>(DamageApply::VT_DAMAGE, damage, 0.0);
            }
            #[inline]
            pub fn add_stagger(&mut self, stagger: bool) {
                self.fbb_
                    .push_slot::<bool>(DamageApply::VT_STAGGER, stagger, false);
            }
            #[inline]
            pub fn add_new_hp(&mut self, new_hp: f32) {
                self.fbb_
                    .push_slot::<f32>(DamageApply::VT_NEW_HP, new_hp, 0.0);
            }
            #[inline]
            pub fn add_server_time_ms(&mut self, server_time_ms: u64) {
                self.fbb_
                    .push_slot::<u64>(DamageApply::VT_SERVER_TIME_MS, server_time_ms, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> DamageApplyBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                DamageApplyBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<DamageApply<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for DamageApply<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("DamageApply");
                ds.field("attacker_player_id", &self.attacker_player_id());
                ds.field("damage", &self.damage());
                ds.field("stagger", &self.stagger());
                ds.field("new_hp", &self.new_hp());
                ds.field("server_time_ms", &self.server_time_ms());
                ds.finish()
            }
        }
    } // pub mod v1
} // pub mod skyrim_relive
