// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LIFECYCLE_SKYRIM_RELIVE_V1_H_
#define FLATBUFFERS_GENERATED_LIFECYCLE_SKYRIM_RELIVE_V1_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "types_generated.h"

namespace skyrim_relive {
namespace v1 {

struct Hello;
struct HelloBuilder;

struct Welcome;
struct WelcomeBuilder;

struct Heartbeat;
struct HeartbeatBuilder;

struct LeaveNotify;
struct LeaveNotifyBuilder;

struct Disconnect;
struct DisconnectBuilder;

struct Hello FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HelloBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_CLIENT_PROTOCOL_VERSION = 6,
    VT_CHARACTER_NAME = 8,
    VT_CHARACTER_LEVEL = 10,
    VT_TOP_SKILLS = 12
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint8_t client_protocol_version() const {
    return GetField<uint8_t>(VT_CLIENT_PROTOCOL_VERSION, 0);
  }
  const ::flatbuffers::String *character_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHARACTER_NAME);
  }
  uint16_t character_level() const {
    return GetField<uint16_t>(VT_CHARACTER_LEVEL, 1);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::SkillEntry>> *top_skills() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::SkillEntry>> *>(VT_TOP_SKILLS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_CLIENT_PROTOCOL_VERSION, 1) &&
           VerifyOffset(verifier, VT_CHARACTER_NAME) &&
           verifier.VerifyString(character_name()) &&
           VerifyField<uint16_t>(verifier, VT_CHARACTER_LEVEL, 2) &&
           VerifyOffset(verifier, VT_TOP_SKILLS) &&
           verifier.VerifyVector(top_skills()) &&
           verifier.VerifyVectorOfTables(top_skills()) &&
           verifier.EndTable();
  }
};

struct HelloBuilder {
  typedef Hello Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Hello::VT_NAME, name);
  }
  void add_client_protocol_version(uint8_t client_protocol_version) {
    fbb_.AddElement<uint8_t>(Hello::VT_CLIENT_PROTOCOL_VERSION, client_protocol_version, 0);
  }
  void add_character_name(::flatbuffers::Offset<::flatbuffers::String> character_name) {
    fbb_.AddOffset(Hello::VT_CHARACTER_NAME, character_name);
  }
  void add_character_level(uint16_t character_level) {
    fbb_.AddElement<uint16_t>(Hello::VT_CHARACTER_LEVEL, character_level, 1);
  }
  void add_top_skills(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::SkillEntry>>> top_skills) {
    fbb_.AddOffset(Hello::VT_TOP_SKILLS, top_skills);
  }
  explicit HelloBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Hello> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Hello>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Hello> CreateHello(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint8_t client_protocol_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> character_name = 0,
    uint16_t character_level = 1,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::SkillEntry>>> top_skills = 0) {
  HelloBuilder builder_(_fbb);
  builder_.add_top_skills(top_skills);
  builder_.add_character_name(character_name);
  builder_.add_name(name);
  builder_.add_character_level(character_level);
  builder_.add_client_protocol_version(client_protocol_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Hello> CreateHelloDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint8_t client_protocol_version = 0,
    const char *character_name = nullptr,
    uint16_t character_level = 1,
    const std::vector<::flatbuffers::Offset<skyrim_relive::v1::SkillEntry>> *top_skills = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto character_name__ = character_name ? _fbb.CreateString(character_name) : 0;
  auto top_skills__ = top_skills ? _fbb.CreateVector<::flatbuffers::Offset<skyrim_relive::v1::SkillEntry>>(*top_skills) : 0;
  return skyrim_relive::v1::CreateHello(
      _fbb,
      name__,
      client_protocol_version,
      character_name__,
      character_level,
      top_skills__);
}

struct Welcome FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WelcomeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_SERVER_TICK_RATE_HZ = 6,
    VT_SERVER_SNAPSHOT_RATE_HZ = 8,
    VT_YOUR_ADDR = 10
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint8_t server_tick_rate_hz() const {
    return GetField<uint8_t>(VT_SERVER_TICK_RATE_HZ, 0);
  }
  uint8_t server_snapshot_rate_hz() const {
    return GetField<uint8_t>(VT_SERVER_SNAPSHOT_RATE_HZ, 0);
  }
  const ::flatbuffers::String *your_addr() const {
    return GetPointer<const ::flatbuffers::String *>(VT_YOUR_ADDR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_SERVER_TICK_RATE_HZ, 1) &&
           VerifyField<uint8_t>(verifier, VT_SERVER_SNAPSHOT_RATE_HZ, 1) &&
           VerifyOffset(verifier, VT_YOUR_ADDR) &&
           verifier.VerifyString(your_addr()) &&
           verifier.EndTable();
  }
};

struct WelcomeBuilder {
  typedef Welcome Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(Welcome::VT_PLAYER_ID, player_id, 0);
  }
  void add_server_tick_rate_hz(uint8_t server_tick_rate_hz) {
    fbb_.AddElement<uint8_t>(Welcome::VT_SERVER_TICK_RATE_HZ, server_tick_rate_hz, 0);
  }
  void add_server_snapshot_rate_hz(uint8_t server_snapshot_rate_hz) {
    fbb_.AddElement<uint8_t>(Welcome::VT_SERVER_SNAPSHOT_RATE_HZ, server_snapshot_rate_hz, 0);
  }
  void add_your_addr(::flatbuffers::Offset<::flatbuffers::String> your_addr) {
    fbb_.AddOffset(Welcome::VT_YOUR_ADDR, your_addr);
  }
  explicit WelcomeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Welcome> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Welcome>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Welcome> CreateWelcome(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint8_t server_tick_rate_hz = 0,
    uint8_t server_snapshot_rate_hz = 0,
    ::flatbuffers::Offset<::flatbuffers::String> your_addr = 0) {
  WelcomeBuilder builder_(_fbb);
  builder_.add_your_addr(your_addr);
  builder_.add_player_id(player_id);
  builder_.add_server_snapshot_rate_hz(server_snapshot_rate_hz);
  builder_.add_server_tick_rate_hz(server_tick_rate_hz);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Welcome> CreateWelcomeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint8_t server_tick_rate_hz = 0,
    uint8_t server_snapshot_rate_hz = 0,
    const char *your_addr = nullptr) {
  auto your_addr__ = your_addr ? _fbb.CreateString(your_addr) : 0;
  return skyrim_relive::v1::CreateWelcome(
      _fbb,
      player_id,
      server_tick_rate_hz,
      server_snapshot_rate_hz,
      your_addr__);
}

struct Heartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_TIME_MS = 4
  };
  uint64_t client_time_ms() const {
    return GetField<uint64_t>(VT_CLIENT_TIME_MS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIME_MS, 8) &&
           verifier.EndTable();
  }
};

struct HeartbeatBuilder {
  typedef Heartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_time_ms(uint64_t client_time_ms) {
    fbb_.AddElement<uint64_t>(Heartbeat::VT_CLIENT_TIME_MS, client_time_ms, 0);
  }
  explicit HeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Heartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Heartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_time_ms = 0) {
  HeartbeatBuilder builder_(_fbb);
  builder_.add_client_time_ms(client_time_ms);
  return builder_.Finish();
}

struct LeaveNotify FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LeaveNotifyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REASON = 4
  };
  const ::flatbuffers::String *reason() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           verifier.EndTable();
  }
};

struct LeaveNotifyBuilder {
  typedef LeaveNotify Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reason(::flatbuffers::Offset<::flatbuffers::String> reason) {
    fbb_.AddOffset(LeaveNotify::VT_REASON, reason);
  }
  explicit LeaveNotifyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LeaveNotify> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LeaveNotify>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LeaveNotify> CreateLeaveNotify(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> reason = 0) {
  LeaveNotifyBuilder builder_(_fbb);
  builder_.add_reason(reason);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LeaveNotify> CreateLeaveNotifyDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *reason = nullptr) {
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return skyrim_relive::v1::CreateLeaveNotify(
      _fbb,
      reason__);
}

struct Disconnect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DisconnectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_REASON = 6
  };
  skyrim_relive::v1::DisconnectCode code() const {
    return static_cast<skyrim_relive::v1::DisconnectCode>(GetField<uint8_t>(VT_CODE, 0));
  }
  const ::flatbuffers::String *reason() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CODE, 1) &&
           VerifyOffset(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           verifier.EndTable();
  }
};

struct DisconnectBuilder {
  typedef Disconnect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(skyrim_relive::v1::DisconnectCode code) {
    fbb_.AddElement<uint8_t>(Disconnect::VT_CODE, static_cast<uint8_t>(code), 0);
  }
  void add_reason(::flatbuffers::Offset<::flatbuffers::String> reason) {
    fbb_.AddOffset(Disconnect::VT_REASON, reason);
  }
  explicit DisconnectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Disconnect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Disconnect>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Disconnect> CreateDisconnect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    skyrim_relive::v1::DisconnectCode code = skyrim_relive::v1::DisconnectCode_Ok,
    ::flatbuffers::Offset<::flatbuffers::String> reason = 0) {
  DisconnectBuilder builder_(_fbb);
  builder_.add_reason(reason);
  builder_.add_code(code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Disconnect> CreateDisconnectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    skyrim_relive::v1::DisconnectCode code = skyrim_relive::v1::DisconnectCode_Ok,
    const char *reason = nullptr) {
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return skyrim_relive::v1::CreateDisconnect(
      _fbb,
      code,
      reason__);
}

}  // namespace v1
}  // namespace skyrim_relive

#endif  // FLATBUFFERS_GENERATED_LIFECYCLE_SKYRIM_RELIVE_V1_H_
