// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TYPES_SKYRIM_RELIVE_V1_H_
#define FLATBUFFERS_GENERATED_TYPES_SKYRIM_RELIVE_V1_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace skyrim_relive {
namespace v1 {

enum MessageType : uint8_t {
  MessageType_Hello = 1,
  MessageType_Welcome = 2,
  MessageType_Heartbeat = 3,
  MessageType_LeaveNotify = 4,
  MessageType_Disconnect = 5,
  MessageType_PlayerInput = 16,
  MessageType_WorldSnapshot = 17,
  MessageType_CombatEvent = 32,
  MessageType_DamageApply = 33,
  MessageType_MIN = MessageType_Hello,
  MessageType_MAX = MessageType_DamageApply
};

inline const MessageType (&EnumValuesMessageType())[9] {
  static const MessageType values[] = {
    MessageType_Hello,
    MessageType_Welcome,
    MessageType_Heartbeat,
    MessageType_LeaveNotify,
    MessageType_Disconnect,
    MessageType_PlayerInput,
    MessageType_WorldSnapshot,
    MessageType_CombatEvent,
    MessageType_DamageApply
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[34] = {
    "Hello",
    "Welcome",
    "Heartbeat",
    "LeaveNotify",
    "Disconnect",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "PlayerInput",
    "WorldSnapshot",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "CombatEvent",
    "DamageApply",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (::flatbuffers::IsOutRange(e, MessageType_Hello, MessageType_DamageApply)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(MessageType_Hello);
  return EnumNamesMessageType()[index];
}

enum DisconnectCode : uint8_t {
  DisconnectCode_Ok = 0,
  DisconnectCode_VersionMismatch = 1,
  DisconnectCode_Timeout = 2,
  DisconnectCode_ServerFull = 3,
  DisconnectCode_ServerShutdown = 4,
  DisconnectCode_BadPacket = 5,
  DisconnectCode_DuplicateName = 6,
  DisconnectCode_MIN = DisconnectCode_Ok,
  DisconnectCode_MAX = DisconnectCode_DuplicateName
};

inline const DisconnectCode (&EnumValuesDisconnectCode())[7] {
  static const DisconnectCode values[] = {
    DisconnectCode_Ok,
    DisconnectCode_VersionMismatch,
    DisconnectCode_Timeout,
    DisconnectCode_ServerFull,
    DisconnectCode_ServerShutdown,
    DisconnectCode_BadPacket,
    DisconnectCode_DuplicateName
  };
  return values;
}

inline const char * const *EnumNamesDisconnectCode() {
  static const char * const names[8] = {
    "Ok",
    "VersionMismatch",
    "Timeout",
    "ServerFull",
    "ServerShutdown",
    "BadPacket",
    "DuplicateName",
    nullptr
  };
  return names;
}

inline const char *EnumNameDisconnectCode(DisconnectCode e) {
  if (::flatbuffers::IsOutRange(e, DisconnectCode_Ok, DisconnectCode_DuplicateName)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDisconnectCode()[index];
}

}  // namespace v1
}  // namespace skyrim_relive

#endif  // FLATBUFFERS_GENERATED_TYPES_SKYRIM_RELIVE_V1_H_
