// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TYPES_SKYRIM_RELIVE_V1_H_
#define FLATBUFFERS_GENERATED_TYPES_SKYRIM_RELIVE_V1_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace skyrim_relive {
namespace v1 {

struct SkillEntry;
struct SkillEntryBuilder;

enum MessageType : uint8_t {
  MessageType_Hello = 1,
  MessageType_Welcome = 2,
  MessageType_Heartbeat = 3,
  MessageType_LeaveNotify = 4,
  MessageType_Disconnect = 5,
  MessageType_PlayerInput = 16,
  MessageType_WorldSnapshot = 17,
  MessageType_CombatEvent = 32,
  MessageType_DamageApply = 33,
  MessageType_PlayerList = 48,
  MessageType_MIN = MessageType_Hello,
  MessageType_MAX = MessageType_PlayerList
};

inline const MessageType (&EnumValuesMessageType())[10] {
  static const MessageType values[] = {
    MessageType_Hello,
    MessageType_Welcome,
    MessageType_Heartbeat,
    MessageType_LeaveNotify,
    MessageType_Disconnect,
    MessageType_PlayerInput,
    MessageType_WorldSnapshot,
    MessageType_CombatEvent,
    MessageType_DamageApply,
    MessageType_PlayerList
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[49] = {
    "Hello",
    "Welcome",
    "Heartbeat",
    "LeaveNotify",
    "Disconnect",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "PlayerInput",
    "WorldSnapshot",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "CombatEvent",
    "DamageApply",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "PlayerList",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (::flatbuffers::IsOutRange(e, MessageType_Hello, MessageType_PlayerList)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(MessageType_Hello);
  return EnumNamesMessageType()[index];
}

enum DisconnectCode : uint8_t {
  DisconnectCode_Ok = 0,
  DisconnectCode_VersionMismatch = 1,
  DisconnectCode_Timeout = 2,
  DisconnectCode_ServerFull = 3,
  DisconnectCode_ServerShutdown = 4,
  DisconnectCode_BadPacket = 5,
  DisconnectCode_DuplicateName = 6,
  DisconnectCode_MIN = DisconnectCode_Ok,
  DisconnectCode_MAX = DisconnectCode_DuplicateName
};

inline const DisconnectCode (&EnumValuesDisconnectCode())[7] {
  static const DisconnectCode values[] = {
    DisconnectCode_Ok,
    DisconnectCode_VersionMismatch,
    DisconnectCode_Timeout,
    DisconnectCode_ServerFull,
    DisconnectCode_ServerShutdown,
    DisconnectCode_BadPacket,
    DisconnectCode_DuplicateName
  };
  return values;
}

inline const char * const *EnumNamesDisconnectCode() {
  static const char * const names[8] = {
    "Ok",
    "VersionMismatch",
    "Timeout",
    "ServerFull",
    "ServerShutdown",
    "BadPacket",
    "DuplicateName",
    nullptr
  };
  return names;
}

inline const char *EnumNameDisconnectCode(DisconnectCode e) {
  if (::flatbuffers::IsOutRange(e, DisconnectCode_Ok, DisconnectCode_DuplicateName)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDisconnectCode()[index];
}

struct SkillEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SkillEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_LEVEL = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  float level() const {
    return GetField<float>(VT_LEVEL, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_LEVEL, 4) &&
           verifier.EndTable();
  }
};

struct SkillEntryBuilder {
  typedef SkillEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(SkillEntry::VT_NAME, name);
  }
  void add_level(float level) {
    fbb_.AddElement<float>(SkillEntry::VT_LEVEL, level, 0.0f);
  }
  explicit SkillEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SkillEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SkillEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SkillEntry> CreateSkillEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    float level = 0.0f) {
  SkillEntryBuilder builder_(_fbb);
  builder_.add_level(level);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SkillEntry> CreateSkillEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float level = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return skyrim_relive::v1::CreateSkillEntry(
      _fbb,
      name__,
      level);
}

}  // namespace v1
}  // namespace skyrim_relive

#endif  // FLATBUFFERS_GENERATED_TYPES_SKYRIM_RELIVE_V1_H_
