// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WORLD_SKYRIM_RELIVE_V1_H_
#define FLATBUFFERS_GENERATED_WORLD_SKYRIM_RELIVE_V1_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace skyrim_relive {
namespace v1 {

struct Vec3;

struct Transform;

struct PlayerState;

struct PlayerInput;
struct PlayerInputBuilder;

struct WorldSnapshot;
struct WorldSnapshotBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Transform FLATBUFFERS_FINAL_CLASS {
 private:
  skyrim_relive::v1::Vec3 pos_;
  float yaw_;

 public:
  Transform()
      : pos_(),
        yaw_(0) {
  }
  Transform(const skyrim_relive::v1::Vec3 &_pos, float _yaw)
      : pos_(_pos),
        yaw_(::flatbuffers::EndianScalar(_yaw)) {
  }
  const skyrim_relive::v1::Vec3 &pos() const {
    return pos_;
  }
  float yaw() const {
    return ::flatbuffers::EndianScalar(yaw_);
  }
};
FLATBUFFERS_STRUCT_END(Transform, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PlayerState FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t player_id_;
  skyrim_relive::v1::Transform transform_;

 public:
  PlayerState()
      : player_id_(0),
        transform_() {
  }
  PlayerState(uint32_t _player_id, const skyrim_relive::v1::Transform &_transform)
      : player_id_(::flatbuffers::EndianScalar(_player_id)),
        transform_(_transform) {
  }
  uint32_t player_id() const {
    return ::flatbuffers::EndianScalar(player_id_);
  }
  const skyrim_relive::v1::Transform &transform() const {
    return transform_;
  }
};
FLATBUFFERS_STRUCT_END(PlayerState, 20);

struct PlayerInput FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerInputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSFORM = 4,
    VT_CLIENT_TIME_MS = 6
  };
  const skyrim_relive::v1::Transform *transform() const {
    return GetStruct<const skyrim_relive::v1::Transform *>(VT_TRANSFORM);
  }
  uint64_t client_time_ms() const {
    return GetField<uint64_t>(VT_CLIENT_TIME_MS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<skyrim_relive::v1::Transform>(verifier, VT_TRANSFORM, 4) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIME_MS, 8) &&
           verifier.EndTable();
  }
};

struct PlayerInputBuilder {
  typedef PlayerInput Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transform(const skyrim_relive::v1::Transform *transform) {
    fbb_.AddStruct(PlayerInput::VT_TRANSFORM, transform);
  }
  void add_client_time_ms(uint64_t client_time_ms) {
    fbb_.AddElement<uint64_t>(PlayerInput::VT_CLIENT_TIME_MS, client_time_ms, 0);
  }
  explicit PlayerInputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerInput> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerInput>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerInput> CreatePlayerInput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const skyrim_relive::v1::Transform *transform = nullptr,
    uint64_t client_time_ms = 0) {
  PlayerInputBuilder builder_(_fbb);
  builder_.add_client_time_ms(client_time_ms);
  builder_.add_transform(transform);
  return builder_.Finish();
}

struct WorldSnapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorldSnapshotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_TICK = 4,
    VT_SERVER_TIME_MS = 6,
    VT_PLAYERS = 8
  };
  uint64_t server_tick() const {
    return GetField<uint64_t>(VT_SERVER_TICK, 0);
  }
  uint64_t server_time_ms() const {
    return GetField<uint64_t>(VT_SERVER_TIME_MS, 0);
  }
  const ::flatbuffers::Vector<const skyrim_relive::v1::PlayerState *> *players() const {
    return GetPointer<const ::flatbuffers::Vector<const skyrim_relive::v1::PlayerState *> *>(VT_PLAYERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TICK, 8) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME_MS, 8) &&
           VerifyOffset(verifier, VT_PLAYERS) &&
           verifier.VerifyVector(players()) &&
           verifier.EndTable();
  }
};

struct WorldSnapshotBuilder {
  typedef WorldSnapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_tick(uint64_t server_tick) {
    fbb_.AddElement<uint64_t>(WorldSnapshot::VT_SERVER_TICK, server_tick, 0);
  }
  void add_server_time_ms(uint64_t server_time_ms) {
    fbb_.AddElement<uint64_t>(WorldSnapshot::VT_SERVER_TIME_MS, server_time_ms, 0);
  }
  void add_players(::flatbuffers::Offset<::flatbuffers::Vector<const skyrim_relive::v1::PlayerState *>> players) {
    fbb_.AddOffset(WorldSnapshot::VT_PLAYERS, players);
  }
  explicit WorldSnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WorldSnapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WorldSnapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WorldSnapshot> CreateWorldSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t server_tick = 0,
    uint64_t server_time_ms = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const skyrim_relive::v1::PlayerState *>> players = 0) {
  WorldSnapshotBuilder builder_(_fbb);
  builder_.add_server_time_ms(server_time_ms);
  builder_.add_server_tick(server_tick);
  builder_.add_players(players);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WorldSnapshot> CreateWorldSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t server_tick = 0,
    uint64_t server_time_ms = 0,
    const std::vector<skyrim_relive::v1::PlayerState> *players = nullptr) {
  auto players__ = players ? _fbb.CreateVectorOfStructs<skyrim_relive::v1::PlayerState>(*players) : 0;
  return skyrim_relive::v1::CreateWorldSnapshot(
      _fbb,
      server_tick,
      server_time_ms,
      players__);
}

}  // namespace v1
}  // namespace skyrim_relive

#endif  // FLATBUFFERS_GENERATED_WORLD_SKYRIM_RELIVE_V1_H_
