// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WORLD_SKYRIM_RELIVE_V1_H_
#define FLATBUFFERS_GENERATED_WORLD_SKYRIM_RELIVE_V1_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace skyrim_relive {
namespace v1 {

struct Vec3;

struct Transform;

struct PlayerState;
struct PlayerStateBuilder;

struct PlayerInput;
struct PlayerInputBuilder;

struct WorldSnapshot;
struct WorldSnapshotBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Transform FLATBUFFERS_FINAL_CLASS {
 private:
  skyrim_relive::v1::Vec3 pos_;
  float yaw_;

 public:
  Transform()
      : pos_(),
        yaw_(0) {
  }
  Transform(const skyrim_relive::v1::Vec3 &_pos, float _yaw)
      : pos_(_pos),
        yaw_(::flatbuffers::EndianScalar(_yaw)) {
  }
  const skyrim_relive::v1::Vec3 &pos() const {
    return pos_;
  }
  float yaw() const {
    return ::flatbuffers::EndianScalar(yaw_);
  }
};
FLATBUFFERS_STRUCT_END(Transform, 16);

struct PlayerState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_TRANSFORM = 6,
    VT_ANIM_SPEED = 8,
    VT_ANIM_DIRECTION = 10,
    VT_ANIM_IS_RUNNING = 12,
    VT_ANIM_IS_SPRINTING = 14,
    VT_ANIM_IS_SNEAKING = 16
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  const skyrim_relive::v1::Transform *transform() const {
    return GetStruct<const skyrim_relive::v1::Transform *>(VT_TRANSFORM);
  }
  float anim_speed() const {
    return GetField<float>(VT_ANIM_SPEED, 0.0f);
  }
  float anim_direction() const {
    return GetField<float>(VT_ANIM_DIRECTION, 0.0f);
  }
  bool anim_is_running() const {
    return GetField<uint8_t>(VT_ANIM_IS_RUNNING, 0) != 0;
  }
  bool anim_is_sprinting() const {
    return GetField<uint8_t>(VT_ANIM_IS_SPRINTING, 0) != 0;
  }
  bool anim_is_sneaking() const {
    return GetField<uint8_t>(VT_ANIM_IS_SNEAKING, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<skyrim_relive::v1::Transform>(verifier, VT_TRANSFORM, 4) &&
           VerifyField<float>(verifier, VT_ANIM_SPEED, 4) &&
           VerifyField<float>(verifier, VT_ANIM_DIRECTION, 4) &&
           VerifyField<uint8_t>(verifier, VT_ANIM_IS_RUNNING, 1) &&
           VerifyField<uint8_t>(verifier, VT_ANIM_IS_SPRINTING, 1) &&
           VerifyField<uint8_t>(verifier, VT_ANIM_IS_SNEAKING, 1) &&
           verifier.EndTable();
  }
};

struct PlayerStateBuilder {
  typedef PlayerState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(PlayerState::VT_PLAYER_ID, player_id, 0);
  }
  void add_transform(const skyrim_relive::v1::Transform *transform) {
    fbb_.AddStruct(PlayerState::VT_TRANSFORM, transform);
  }
  void add_anim_speed(float anim_speed) {
    fbb_.AddElement<float>(PlayerState::VT_ANIM_SPEED, anim_speed, 0.0f);
  }
  void add_anim_direction(float anim_direction) {
    fbb_.AddElement<float>(PlayerState::VT_ANIM_DIRECTION, anim_direction, 0.0f);
  }
  void add_anim_is_running(bool anim_is_running) {
    fbb_.AddElement<uint8_t>(PlayerState::VT_ANIM_IS_RUNNING, static_cast<uint8_t>(anim_is_running), 0);
  }
  void add_anim_is_sprinting(bool anim_is_sprinting) {
    fbb_.AddElement<uint8_t>(PlayerState::VT_ANIM_IS_SPRINTING, static_cast<uint8_t>(anim_is_sprinting), 0);
  }
  void add_anim_is_sneaking(bool anim_is_sneaking) {
    fbb_.AddElement<uint8_t>(PlayerState::VT_ANIM_IS_SNEAKING, static_cast<uint8_t>(anim_is_sneaking), 0);
  }
  explicit PlayerStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerState> CreatePlayerState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    const skyrim_relive::v1::Transform *transform = nullptr,
    float anim_speed = 0.0f,
    float anim_direction = 0.0f,
    bool anim_is_running = false,
    bool anim_is_sprinting = false,
    bool anim_is_sneaking = false) {
  PlayerStateBuilder builder_(_fbb);
  builder_.add_anim_direction(anim_direction);
  builder_.add_anim_speed(anim_speed);
  builder_.add_transform(transform);
  builder_.add_player_id(player_id);
  builder_.add_anim_is_sneaking(anim_is_sneaking);
  builder_.add_anim_is_sprinting(anim_is_sprinting);
  builder_.add_anim_is_running(anim_is_running);
  return builder_.Finish();
}

struct PlayerInput FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerInputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSFORM = 4,
    VT_CLIENT_TIME_MS = 6,
    VT_ANIM_SPEED = 8,
    VT_ANIM_DIRECTION = 10,
    VT_ANIM_IS_RUNNING = 12,
    VT_ANIM_IS_SPRINTING = 14,
    VT_ANIM_IS_SNEAKING = 16
  };
  const skyrim_relive::v1::Transform *transform() const {
    return GetStruct<const skyrim_relive::v1::Transform *>(VT_TRANSFORM);
  }
  uint64_t client_time_ms() const {
    return GetField<uint64_t>(VT_CLIENT_TIME_MS, 0);
  }
  float anim_speed() const {
    return GetField<float>(VT_ANIM_SPEED, 0.0f);
  }
  float anim_direction() const {
    return GetField<float>(VT_ANIM_DIRECTION, 0.0f);
  }
  bool anim_is_running() const {
    return GetField<uint8_t>(VT_ANIM_IS_RUNNING, 0) != 0;
  }
  bool anim_is_sprinting() const {
    return GetField<uint8_t>(VT_ANIM_IS_SPRINTING, 0) != 0;
  }
  bool anim_is_sneaking() const {
    return GetField<uint8_t>(VT_ANIM_IS_SNEAKING, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<skyrim_relive::v1::Transform>(verifier, VT_TRANSFORM, 4) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIME_MS, 8) &&
           VerifyField<float>(verifier, VT_ANIM_SPEED, 4) &&
           VerifyField<float>(verifier, VT_ANIM_DIRECTION, 4) &&
           VerifyField<uint8_t>(verifier, VT_ANIM_IS_RUNNING, 1) &&
           VerifyField<uint8_t>(verifier, VT_ANIM_IS_SPRINTING, 1) &&
           VerifyField<uint8_t>(verifier, VT_ANIM_IS_SNEAKING, 1) &&
           verifier.EndTable();
  }
};

struct PlayerInputBuilder {
  typedef PlayerInput Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transform(const skyrim_relive::v1::Transform *transform) {
    fbb_.AddStruct(PlayerInput::VT_TRANSFORM, transform);
  }
  void add_client_time_ms(uint64_t client_time_ms) {
    fbb_.AddElement<uint64_t>(PlayerInput::VT_CLIENT_TIME_MS, client_time_ms, 0);
  }
  void add_anim_speed(float anim_speed) {
    fbb_.AddElement<float>(PlayerInput::VT_ANIM_SPEED, anim_speed, 0.0f);
  }
  void add_anim_direction(float anim_direction) {
    fbb_.AddElement<float>(PlayerInput::VT_ANIM_DIRECTION, anim_direction, 0.0f);
  }
  void add_anim_is_running(bool anim_is_running) {
    fbb_.AddElement<uint8_t>(PlayerInput::VT_ANIM_IS_RUNNING, static_cast<uint8_t>(anim_is_running), 0);
  }
  void add_anim_is_sprinting(bool anim_is_sprinting) {
    fbb_.AddElement<uint8_t>(PlayerInput::VT_ANIM_IS_SPRINTING, static_cast<uint8_t>(anim_is_sprinting), 0);
  }
  void add_anim_is_sneaking(bool anim_is_sneaking) {
    fbb_.AddElement<uint8_t>(PlayerInput::VT_ANIM_IS_SNEAKING, static_cast<uint8_t>(anim_is_sneaking), 0);
  }
  explicit PlayerInputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerInput> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerInput>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerInput> CreatePlayerInput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const skyrim_relive::v1::Transform *transform = nullptr,
    uint64_t client_time_ms = 0,
    float anim_speed = 0.0f,
    float anim_direction = 0.0f,
    bool anim_is_running = false,
    bool anim_is_sprinting = false,
    bool anim_is_sneaking = false) {
  PlayerInputBuilder builder_(_fbb);
  builder_.add_client_time_ms(client_time_ms);
  builder_.add_anim_direction(anim_direction);
  builder_.add_anim_speed(anim_speed);
  builder_.add_transform(transform);
  builder_.add_anim_is_sneaking(anim_is_sneaking);
  builder_.add_anim_is_sprinting(anim_is_sprinting);
  builder_.add_anim_is_running(anim_is_running);
  return builder_.Finish();
}

struct WorldSnapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorldSnapshotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_TICK = 4,
    VT_SERVER_TIME_MS = 6,
    VT_PLAYERS = 8
  };
  uint64_t server_tick() const {
    return GetField<uint64_t>(VT_SERVER_TICK, 0);
  }
  uint64_t server_time_ms() const {
    return GetField<uint64_t>(VT_SERVER_TIME_MS, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::PlayerState>> *players() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::PlayerState>> *>(VT_PLAYERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TICK, 8) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME_MS, 8) &&
           VerifyOffset(verifier, VT_PLAYERS) &&
           verifier.VerifyVector(players()) &&
           verifier.VerifyVectorOfTables(players()) &&
           verifier.EndTable();
  }
};

struct WorldSnapshotBuilder {
  typedef WorldSnapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_tick(uint64_t server_tick) {
    fbb_.AddElement<uint64_t>(WorldSnapshot::VT_SERVER_TICK, server_tick, 0);
  }
  void add_server_time_ms(uint64_t server_time_ms) {
    fbb_.AddElement<uint64_t>(WorldSnapshot::VT_SERVER_TIME_MS, server_time_ms, 0);
  }
  void add_players(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::PlayerState>>> players) {
    fbb_.AddOffset(WorldSnapshot::VT_PLAYERS, players);
  }
  explicit WorldSnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WorldSnapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WorldSnapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WorldSnapshot> CreateWorldSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t server_tick = 0,
    uint64_t server_time_ms = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skyrim_relive::v1::PlayerState>>> players = 0) {
  WorldSnapshotBuilder builder_(_fbb);
  builder_.add_server_time_ms(server_time_ms);
  builder_.add_server_tick(server_tick);
  builder_.add_players(players);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WorldSnapshot> CreateWorldSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t server_tick = 0,
    uint64_t server_time_ms = 0,
    const std::vector<::flatbuffers::Offset<skyrim_relive::v1::PlayerState>> *players = nullptr) {
  auto players__ = players ? _fbb.CreateVector<::flatbuffers::Offset<skyrim_relive::v1::PlayerState>>(*players) : 0;
  return skyrim_relive::v1::CreateWorldSnapshot(
      _fbb,
      server_tick,
      server_time_ms,
      players__);
}

}  // namespace v1
}  // namespace skyrim_relive

#endif  // FLATBUFFERS_GENERATED_WORLD_SKYRIM_RELIVE_V1_H_
